{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.6.0-alpha02.aar",
          "url": "appcompat-resources-1.6.0-alpha02.aar",
          "size": 67102,
          "sha512": "1272fda0cd0e0dc264651083f7d098aa29b54c795fc31958465274dccbe76bafc916f833b9c36d76928a2f5630e3132dcdae5424649b186a6d910a6e70ef657b",
          "sha256": "0061335f9d1204c3e1b3a63ae2d8b9fb85cfa3773147c0e525c12e77ac348010",
          "sha1": "5c8f10b9b13660abf67f1d87efddbc567d0833b7",
          "md5": "f9addb60eacce944e3b6931a4277cb02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.6.0-alpha02.aar",
          "url": "appcompat-resources-1.6.0-alpha02.aar",
          "size": 67102,
          "sha512": "1272fda0cd0e0dc264651083f7d098aa29b54c795fc31958465274dccbe76bafc916f833b9c36d76928a2f5630e3132dcdae5424649b186a6d910a6e70ef657b",
          "sha256": "0061335f9d1204c3e1b3a63ae2d8b9fb85cfa3773147c0e525c12e77ac348010",
          "sha1": "5c8f10b9b13660abf67f1d87efddbc567d0833b7",
          "md5": "f9addb60eacce944e3b6931a4277cb02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.6.0-alpha02-sources.jar",
          "url": "appcompat-resources-1.6.0-alpha02-sources.jar",
          "size": 40855,
          "sha512": "6dbc472b68da1cf1e7c08973d9f796881ca59ab21bc922580d3ca8b07b206a50e07d9751cfc802d580cff5d08aa2f7dd84061cd090397328d14f090d2bc184bf",
          "sha256": "014980c366a1755d486e4cde2ea616cc2074963c5f48ffcb01dee15dd5f9421d",
          "sha1": "8f78838745a125dea62514f7b4f70e8776a6244e",
          "md5": "4e8141afafcbf7ffe9e19ec02207f2e0"
        }
      ]
    }
  ]
}
