{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.print",
    "module": "print",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "print-1.1.0-beta01.aar",
          "url": "print-1.1.0-beta01.aar",
          "size": 16666,
          "sha512": "25d00b281a9753616078358c3e2851b529a684a52a245ddb45507450a25db4086223455a03fb3ce36ba4a7f8f6bb6a9e20e9dc7641f932311154bd1156fea15a",
          "sha256": "6b944a3430eeff8684f178a0bf365366c4874d076df5cdbf6bee33e36e4c627f",
          "sha1": "0022d9c9c2d85d0d7fc14de308c7768bfc21be74",
          "md5": "8728f6d006fb938135bce1cae891d680"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "print-1.1.0-beta01.aar",
          "url": "print-1.1.0-beta01.aar",
          "size": 16666,
          "sha512": "25d00b281a9753616078358c3e2851b529a684a52a245ddb45507450a25db4086223455a03fb3ce36ba4a7f8f6bb6a9e20e9dc7641f932311154bd1156fea15a",
          "sha256": "6b944a3430eeff8684f178a0bf365366c4874d076df5cdbf6bee33e36e4c627f",
          "sha1": "0022d9c9c2d85d0d7fc14de308c7768bfc21be74",
          "md5": "8728f6d006fb938135bce1cae891d680"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "print-1.1.0-beta01-sources.jar",
          "url": "print-1.1.0-beta01-sources.jar",
          "size": 7147,
          "sha512": "f0d5ec60cae194ce29bf798dcf07169d85251bf1dedc73dc7eaf1b53c182c6e4b609e2799f457272baa1b7712f6527d574d234068d7208129725738f808d1cb7",
          "sha256": "b6189b61e826af0d64350f384378615ce84f43aafefe56b6e1af5af848b9abfe",
          "sha1": "f92413583ab7a95882a61b98bc7512878103b6a7",
          "md5": "c1c0e41c6a4059e2146d82ffe85f14cf"
        }
      ]
    }
  ]
}
