{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.viewpager2",
    "module": "viewpager2",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewpager2-1.1.0-beta02.aar",
          "url": "viewpager2-1.1.0-beta02.aar",
          "size": 65982,
          "sha512": "d8e5b3816897696d2abd99a0b1f1a00d1fcdebcea5eae6add78c0bcac639f38e0c7c2be36644909ac822a87185472026497ec064e17a768bbad4be4a23521379",
          "sha256": "a07e254562a6264e6bbc9f54785838f1e9ddb583b1162d8a11f99970acab3548",
          "sha1": "3ca5c3b202e98f0ee9f72de67356c228595904ac",
          "md5": "613b4258a9f3f3404f496c85ed998d4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewpager2-1.1.0-beta02.aar",
          "url": "viewpager2-1.1.0-beta02.aar",
          "size": 65982,
          "sha512": "d8e5b3816897696d2abd99a0b1f1a00d1fcdebcea5eae6add78c0bcac639f38e0c7c2be36644909ac822a87185472026497ec064e17a768bbad4be4a23521379",
          "sha256": "a07e254562a6264e6bbc9f54785838f1e9ddb583b1162d8a11f99970acab3548",
          "sha1": "3ca5c3b202e98f0ee9f72de67356c228595904ac",
          "md5": "613b4258a9f3f3404f496c85ed998d4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "viewpager2-1.1.0-beta02-sources.jar",
          "url": "viewpager2-1.1.0-beta02-sources.jar",
          "size": 41229,
          "sha512": "d9f7b4e0561c3f8260a7309ff111fd0b236776052d4d6ff6413e1da328ca1f9b5e927b629293b89771ae8549788cd6d0c8d3e25fc0bfad4c18a1cc2e7fbff708",
          "sha256": "4e5fa3feaeff4b3dff6b1f875a149ae10869ba9d6f84d7cda8dd3a6d189259cb",
          "sha1": "0c9f17c391be6ab7565f6c06f606ace0df3ac066",
          "md5": "7e51bf7f95f0abc35a262d64f1d8b0bd"
        }
      ]
    }
  ]
}
