{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.car.app",
    "module": "app-automotive",
    "version": "1.2.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "app-automotive-1.2.0-beta03.aar",
          "url": "app-automotive-1.2.0-beta03.aar",
          "size": 224779,
          "sha512": "a911126e3a4142f6c4b6aeb4ffc4a4288abae5c3fe13ee94870fd4108a843011428ed1c55b8a05fe0075dcd5044eee91707ca272411a56eeab5eaa50b350f143",
          "sha256": "8e39deb0f0e293404e70b54f39e66a7a6dc24bf197f594ede322479cfe28eb39",
          "sha1": "ae35b3d585228ef692d7644f088c246e50e73aca",
          "md5": "c2b920beec3df464002e9f6b80efe42c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-android"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "androidx.car.app",
          "module": "app",
          "version": {
            "requires": "1.2.0-beta03"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "app-automotive-1.2.0-beta03.aar",
          "url": "app-automotive-1.2.0-beta03.aar",
          "size": 224779,
          "sha512": "a911126e3a4142f6c4b6aeb4ffc4a4288abae5c3fe13ee94870fd4108a843011428ed1c55b8a05fe0075dcd5044eee91707ca272411a56eeab5eaa50b350f143",
          "sha256": "8e39deb0f0e293404e70b54f39e66a7a6dc24bf197f594ede322479cfe28eb39",
          "sha1": "ae35b3d585228ef692d7644f088c246e50e73aca",
          "md5": "c2b920beec3df464002e9f6b80efe42c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "app-automotive-1.2.0-beta03-sources.jar",
          "url": "app-automotive-1.2.0-beta03-sources.jar",
          "size": 60618,
          "sha512": "aeb6804739d706d6884a7d4fa5dc9a771ccd7d46df6fdd517808e4a474ed3f286a5db4109682b3e11d431fb1f5a4053f0bdf789c4067c69983068194ff6676c7",
          "sha256": "1c71d1edce9edc79c18ae39ea7e89afd34e36559b841992a795ff4842d894006",
          "sha1": "02000c0bc90770b22c085de7bdc1e4b54f0d108f",
          "md5": "9b195a645e18cf0cc330e2abc9f3004d"
        }
      ]
    }
  ]
}
