name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Our Bazel builds currently rely on JDK 8.
  USE_JAVA_VERSION: '8'
  # Our Bazel builds currently rely on 3.7.1. The version is set via
  # baselisk by USE_BAZEL_VERSION: https://github.com/bazelbuild/bazelisk.
  USE_BAZEL_VERSION: '3.7.1'

jobs:
  validate-latest-dagger-version:
    name: 'Validate Dagger version'
    runs-on: ubuntu-latest
    steps:
      # Cancel previous runs on the same branch to avoid unnecessary parallel
      # runs of the same job. See https://github.com/google/go-github/pull/1821
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: 'Check out gh-pages repository'
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/gh-pages'
          path: gh-pages
      - name: 'Validate latest Dagger version'
        run: ./gh-pages/.github/scripts/validate-latest-dagger-version.sh gh-pages/_config.yml
  bazel-test:
    name: 'Bazel tests'
    needs: validate-latest-dagger-version
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Java ${{ env.USE_JAVA_VERSION }}'
        uses: actions/setup-java@v1
        with:
          java-version: '${{ env.USE_JAVA_VERSION }}'
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/google/dagger
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Cache Bazel files'
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: 'Cache Gradle files'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Run Bazel tests'
        run: bazel test --test_output=errors //... --keep_going
        shell: bash
      - name: 'Install local snapshot'
        run: ./util/install-local-snapshot.sh
        shell: bash
      - name: 'Upload local snapshot for tests'
        uses: actions/upload-artifact@v2
        with:
          name: local-snapshot
          path: ~/.m2/repository/com/google/dagger
  artifact-java-local-tests:
    name: 'Artifact Java local tests'
    needs: bazel-test
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out repository'
      uses: actions/checkout@v2
    - name: 'Cache Gradle files'
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: 'Download local snapshot for tests'
      uses: actions/download-artifact@v2
      with:
        name: local-snapshot
        path: ~/.m2/repository/com/google/dagger
    - name: 'Gradle Java local tests'
      run: ./util/run-local-gradle-tests.sh
      shell: bash
  artifact-android-local-tests:
    name: 'Artifact Android local tests (AGP ${{ matrix.agp }})'
    needs: bazel-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agp: ['4.1.0', '4.2.0-beta04']
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache Gradle files'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Download local snapshot for tests'
        uses: actions/download-artifact@v2
        with:
          name: local-snapshot
          path: ~/.m2/repository/com/google/dagger
      - name: 'Gradle Android local tests (AGP ${{ matrix.agp }})'
        run: ./util/run-local-gradle-android-tests.sh "${{ matrix.agp }}"
        shell: bash
      - name: 'Upload test reports (AGP ${{ matrix.agp }})'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: tests-reports-agp-${{ matrix.agp }}
          path: ${{ github.workspace }}/**/build/reports/tests/*
  artifact-android-emulator-tests:
    name: 'Artifact Android emulator tests (API 30)'
    needs: bazel-test
    # It's recommended to run emulator tests on macOS
    # See https://github.com/marketplace/actions/android-emulator-runner
    runs-on: macos-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache Gradle files'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Download local snapshot for tests'
        uses: actions/download-artifact@v2
        with:
          name: local-snapshot
          path: ~/.m2/repository/com/google/dagger
      - name: 'Gradle Android emulator tests (API 30)'
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 25
        with:
          api-level: 30
          target: google_apis
          script: ./util/run-local-emulator-tests.sh
      - name: 'Upload test reports (API 30)'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: androidTests-reports-api-30
          path: ${{ github.workspace }}/**/build/reports/androidTests/connected/*
  publish-snapshot:
    name: 'Publish snapshot'
    # TODO(bcorso): Consider also waiting on artifact-android-emulator-tests
    # and artifact-android-emulator-legacy-api-tests after checking flakiness.
    needs: [bazel-test, artifact-java-local-tests, artifact-android-local-tests]
    if: github.event_name == 'push' && github.repository == 'google/dagger' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Java ${{ env.USE_JAVA_VERSION }}'
        uses: actions/setup-java@v1
        with:
          java-version: '${{ env.USE_JAVA_VERSION }}'
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache local Maven repository'
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/com/google/dagger
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: 'Cache Bazel files'
        uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: 'Cache Gradle files'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Publish latest docs'
        run: ./util/generate-latest-docs.sh
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
      - name: 'Publish latest snapshot'
        run: ./util/publish-snapshot-on-commit.sh
        shell: bash
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
  artifact-android-emulator-legacy-api-tests:
    name: 'Artifact Android emulator tests (API ${{ matrix.api-level }})'
    # We only run this on master push (essentially a postsubmit) since these
    # can take a while to run
    if: github.event_name == 'push' && github.repository == 'google/dagger' && github.ref == 'refs/heads/master'
    needs: bazel-test
    # It's recommended to run emulator tests on macOS
    # See https://github.com/marketplace/actions/android-emulator-runner
    runs-on: macos-latest
    strategy:
      matrix: # Run on 16 (PreL), 21 (L), and 26 (O).
        api-level: [16, 21, 26]
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Cache Gradle files'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'Download local snapshot for tests'
        uses: actions/download-artifact@v2
        with:
          name: local-snapshot
          path: ~/.m2/repository/com/google/dagger
      - name: 'Gradle Android emulator tests (API ${{ matrix.api-level }})'
        uses: reactivecircus/android-emulator-runner@v2
        timeout-minutes: 25
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          script: ./util/run-local-emulator-tests.sh
      - name: 'Upload test reports (API ${{ matrix.api-level }})'
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: androidTests-report-api-${{ matrix.api-level }}
          path: ${{ github.workspace }}/**/build/reports/androidTests/connected/*
