{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha10.aar",
          "url": "tracing-perfetto-1.0.0-alpha10.aar",
          "size": 23198,
          "sha512": "b341983daa6ebf7a03e7052a39eae0b996fc5281238ed1752b5044fde21a91d18edc406cfa1614f11184b514b9b83459f79a2a307a04b41c9a4748933d2a96e4",
          "sha256": "7d6a51c25852fb43bb9964de6f68adeed9e93b4b7da23537353648007fe082e7",
          "sha1": "91186b2f2f3a118961c482ff8917257bb8f6dc72",
          "md5": "6d5876c40c3db268ab69a059175f2271"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-common",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha10.aar",
          "url": "tracing-perfetto-1.0.0-alpha10.aar",
          "size": 23198,
          "sha512": "b341983daa6ebf7a03e7052a39eae0b996fc5281238ed1752b5044fde21a91d18edc406cfa1614f11184b514b9b83459f79a2a307a04b41c9a4748933d2a96e4",
          "sha256": "7d6a51c25852fb43bb9964de6f68adeed9e93b4b7da23537353648007fe082e7",
          "sha1": "91186b2f2f3a118961c482ff8917257bb8f6dc72",
          "md5": "6d5876c40c3db268ab69a059175f2271"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-alpha10-sources.jar",
          "url": "tracing-perfetto-1.0.0-alpha10-sources.jar",
          "size": 12039,
          "sha512": "c74c1e0ebed1a866c89680e591b46a12cb70af1075d09279000ba4b0b644cf3393c943996ce05a6172ce150281d155a9af1ef9ed868f583d88b63e054d6d903f",
          "sha256": "723660cbdbdb357738c67c84e9cc36e449d3f33de2c01b364211ddc90ae88381",
          "sha1": "1bf5fef20edf3b5281a2fb8ada156128009c7369",
          "md5": "d9d84e0118adaa77b6bd99315c567605"
        }
      ]
    }
  ]
}