{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha02.aar",
          "url": "recyclerview-1.3.0-alpha02.aar",
          "size": 400248,
          "sha512": "f651ac238f425cdef8bc85949a44c6148a0997500320574c041922c3b9928e195a5fdab22089145b7be61e4e76cbd71655896d21b52c666c8eb1aa727c0296c6",
          "sha256": "e652a12797992a6870d8017c8616935dff7733d292b5b73cf1df3436a8cb9810",
          "sha1": "f1574c4a3e67c96481aabba1635e9932af681cbc",
          "md5": "c629db4a8446191547359f46162068ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha02.aar",
          "url": "recyclerview-1.3.0-alpha02.aar",
          "size": 400248,
          "sha512": "f651ac238f425cdef8bc85949a44c6148a0997500320574c041922c3b9928e195a5fdab22089145b7be61e4e76cbd71655896d21b52c666c8eb1aa727c0296c6",
          "sha256": "e652a12797992a6870d8017c8616935dff7733d292b5b73cf1df3436a8cb9810",
          "sha1": "f1574c4a3e67c96481aabba1635e9932af681cbc",
          "md5": "c629db4a8446191547359f46162068ca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.3.0-alpha02-sources.jar",
          "url": "recyclerview-1.3.0-alpha02-sources.jar",
          "size": 323108,
          "sha512": "3e1db04c85834929574bf4109db4c4a4661318882d7f3d17df04fdbea1a58645bae8b11698e459ab4ae1bd09d4f71966a67afec43be6cb23f619121f27fa824f",
          "sha256": "ef5876f7fedab2a297cde5a328ba4dc8c06f91aca9cc1a3d1a0ba93dc4c257b6",
          "sha1": "51ce457aba00005397eb0001028cfacb4d8509f1",
          "md5": "4dd8f0da129d49be86e3e1659de18bd1"
        }
      ]
    }
  ]
}
