{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.8.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.8.0-alpha02.aar",
          "url": "work-runtime-2.8.0-alpha02.aar",
          "size": 1575483,
          "sha512": "de49e9f51ef0bdfd3458109f015d90e6002a2f559e6213b54526b368f2e046e49ddebd43ae81d9599eb8f7df7c01220ac86bb3eb129461a9d8d8da9893947207",
          "sha256": "e7c637b4c1e619f31018783e43ce5c0851f156713b93f6c27aa31e1613c4c7f0",
          "sha1": "0baeeb2710c4c9b90f46dca186a8e894aa4f7816",
          "md5": "a4a1b2a0aa3d740318816d74e9de5c8b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.8.0-alpha02.aar",
          "url": "work-runtime-2.8.0-alpha02.aar",
          "size": 1575483,
          "sha512": "de49e9f51ef0bdfd3458109f015d90e6002a2f559e6213b54526b368f2e046e49ddebd43ae81d9599eb8f7df7c01220ac86bb3eb129461a9d8d8da9893947207",
          "sha256": "e7c637b4c1e619f31018783e43ce5c0851f156713b93f6c27aa31e1613c4c7f0",
          "sha1": "0baeeb2710c4c9b90f46dca186a8e894aa4f7816",
          "md5": "a4a1b2a0aa3d740318816d74e9de5c8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-2.8.0-alpha02-sources.jar",
          "url": "work-runtime-2.8.0-alpha02-sources.jar",
          "size": 259538,
          "sha512": "23eacce531a5f802c4d284df8f4e108cdeacbe3d82788dc4112d04a285a32e6862643051c8fe070f3b1c85207db35a65e709bf1a470251a61abeccc5ae5541bf",
          "sha256": "96d8ffa6818b6fbc90401f72b924ec46842ebedec93c559446c3d19c248a04ba",
          "sha1": "5e108860b6f61e62aae988c25627b28b641d2a7e",
          "md5": "fb50c6f1df0baced51449b550c9ea6c0"
        }
      ]
    }
  ]
}
