{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recommendation",
    "module": "recommendation",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recommendation-1.1.0-alpha01.aar",
          "url": "recommendation-1.1.0-alpha01.aar",
          "size": 13221,
          "sha512": "5579680b6af1ee869ffff093f6b29bf428eddf050f9842f76aa816ea3f35634f578dc61f5ba1fd6e88d300486a31ffe1a386e68524a34b22438b200be08deabf",
          "sha256": "90a3d4e5da522f768813454690c17cfbb49d45c7104acfe364c5e097a467e6d6",
          "sha1": "c50892eee944515390816eecd8dab3d5d0639d83",
          "md5": "426792d3cea10c0f5379bbf54c9c0d70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "recommendation-1.1.0-alpha01.aar",
          "url": "recommendation-1.1.0-alpha01.aar",
          "size": 13221,
          "sha512": "5579680b6af1ee869ffff093f6b29bf428eddf050f9842f76aa816ea3f35634f578dc61f5ba1fd6e88d300486a31ffe1a386e68524a34b22438b200be08deabf",
          "sha256": "90a3d4e5da522f768813454690c17cfbb49d45c7104acfe364c5e097a467e6d6",
          "sha1": "c50892eee944515390816eecd8dab3d5d0639d83",
          "md5": "426792d3cea10c0f5379bbf54c9c0d70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recommendation-1.1.0-alpha01-sources.jar",
          "url": "recommendation-1.1.0-alpha01-sources.jar",
          "size": 11751,
          "sha512": "5c2b0fd9ef0400d7157b02a4190e2c37a10fea64a3db2ba9a7b908233c253e1124ddb23f2acbc04fe1db3f58e420c63795141baae835caca781ae8ad2f73dd98",
          "sha256": "529697db268529a51c3c8250c671441d37d806b1cd91434db54ba20c04f8d8e0",
          "sha1": "9e0dee3a88c622ad9957c780888d2954c9be541a",
          "md5": "394036952cbc8e7a59dc554d6dd1a77f"
        }
      ]
    }
  ]
}
