{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.drawerlayout",
    "module": "drawerlayout",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "drawerlayout-1.2.0-alpha01.aar",
          "url": "drawerlayout-1.2.0-alpha01.aar",
          "size": 32472,
          "sha512": "a562d45b193c6b5e4b715ced47e9b6de18b124c8a47f8bc428beb2aa202ad8c893942d3141567a9ce9f23e1b95e9c50156c2d4e39abc63cc1879a3084207e751",
          "sha256": "cc88f9fd2d47b8cea20774380a9f7635c25bb0384b7ef76ddb0cbd3ea0d3b957",
          "sha1": "22ff3e0c3b7019eb4c09fba91dbc78c1aa9dfaa4",
          "md5": "43fbde7b60aaa74f75174c279cacce8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "drawerlayout-1.2.0-alpha01.aar",
          "url": "drawerlayout-1.2.0-alpha01.aar",
          "size": 32472,
          "sha512": "a562d45b193c6b5e4b715ced47e9b6de18b124c8a47f8bc428beb2aa202ad8c893942d3141567a9ce9f23e1b95e9c50156c2d4e39abc63cc1879a3084207e751",
          "sha256": "cc88f9fd2d47b8cea20774380a9f7635c25bb0384b7ef76ddb0cbd3ea0d3b957",
          "sha1": "22ff3e0c3b7019eb4c09fba91dbc78c1aa9dfaa4",
          "md5": "43fbde7b60aaa74f75174c279cacce8a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "drawerlayout-1.2.0-alpha01-sources.jar",
          "url": "drawerlayout-1.2.0-alpha01-sources.jar",
          "size": 20641,
          "sha512": "c81af41d8e2d6ba49ce7222b5d2b934a57dd28af083b4bf09970b2ebe3b6733a5238b200a90ae69625dab604645264079f5eee4d36f8eb2341662c133c58391b",
          "sha256": "511856de72d003a0a4c255243a38f6c24dfc8f3b4755e52d0b0e15f693a10791",
          "sha1": "80824ee54cd9fb4742cbdf778d2f51504a622883",
          "md5": "5647e605b1dd6450ecb3246375f6890d"
        }
      ]
    }
  ]
}
