{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.0-alpha03.aar",
          "url": "navigation-common-ktx-2.5.0-alpha03.aar",
          "size": 1780,
          "sha512": "a4bfe4ca832164aac02b36e7d36e88c34148f34a6de171c41e5ec85a42d384733e990ad911ddf617bda3e23baec2831f2a5d0ce81265fc31e7766dac87eac8ae",
          "sha256": "3fcf625e3f97ea3e9790d00790e024467d78b5ef2f51158cac35003c9205b24f",
          "sha1": "19ac35caaf47b3579610e3b0d2dd59fd055c73b7",
          "md5": "0e101de02e338c1110620c9935c8443f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.5.0-alpha03.aar",
          "url": "navigation-common-ktx-2.5.0-alpha03.aar",
          "size": 1780,
          "sha512": "a4bfe4ca832164aac02b36e7d36e88c34148f34a6de171c41e5ec85a42d384733e990ad911ddf617bda3e23baec2831f2a5d0ce81265fc31e7766dac87eac8ae",
          "sha256": "3fcf625e3f97ea3e9790d00790e024467d78b5ef2f51158cac35003c9205b24f",
          "sha1": "19ac35caaf47b3579610e3b0d2dd59fd055c73b7",
          "md5": "0e101de02e338c1110620c9935c8443f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.5.0-alpha03-sources.jar",
          "url": "navigation-common-ktx-2.5.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
