[project]
name = "avatar"
authors = [{name = "Pandora", email = "pandora-core@google.com"}]
readme = "README.md"
dynamic = ["version", "description"]
dependencies = [
    "bt-test-interfaces",
    "bumble",
    "grpcio>=1.41",
    "mobly>=1.11.1"
]

[build-system]
requires = ["flit_core==3.7.1"]
build-backend = "flit_core.buildapi"
