[package]
name = "uwb_core"
version = "0.0.1"
edition = "2018"

[dependencies]
async-trait = "0.1.52"
bytes = "1.1.0"
num-traits = "0.2.14"
log = "0.4.14"
thiserror = "1.0.30"
tokio = {version = "1.14.0", features = ["sync", "rt", "macros", "time"]}

uwb_uci_packets = { path = "../uwb_uci_packets"}

[dev-dependencies]
env_logger = "0.9.0"
