{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.3.0-alpha02.aar",
          "url": "wear-1.3.0-alpha02.aar",
          "size": 307885,
          "sha512": "95d3dd08971ae63db05c7090853502ae4c1f3bd9db97591aa3d4eddebd22b06685e43bd5ef27bcbe7e1e992f55765854314eff6d4a6f616b5f8b9eea9d461c2b",
          "sha256": "63c5019a91da7c65bdab0d352cba9f94bee9b81ae0b11511094e5162ef10f625",
          "sha1": "f077c7056a5382972b99c481a330bc5727417353",
          "md5": "f97cc0fcf237372ce1f823a12386e43e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.3.0-alpha02.aar",
          "url": "wear-1.3.0-alpha02.aar",
          "size": 307885,
          "sha512": "95d3dd08971ae63db05c7090853502ae4c1f3bd9db97591aa3d4eddebd22b06685e43bd5ef27bcbe7e1e992f55765854314eff6d4a6f616b5f8b9eea9d461c2b",
          "sha256": "63c5019a91da7c65bdab0d352cba9f94bee9b81ae0b11511094e5162ef10f625",
          "sha1": "f077c7056a5382972b99c481a330bc5727417353",
          "md5": "f97cc0fcf237372ce1f823a12386e43e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-1.3.0-alpha02-sources.jar",
          "url": "wear-1.3.0-alpha02-sources.jar",
          "size": 137102,
          "sha512": "01a308722e87e5b49e09ff3fcd979d93bd34333efb69135d64bfb813bbe1b4e2f95c88686135fd5e79924824fa10c4749df3d16b9e9349aa91a8e1c752556749",
          "sha256": "5e135958e267d7faf2ae5cfdd8f2033c565226dea75f8d2d300cef778fa87960",
          "sha1": "7dcd73ec3c913898b15f918d396ba10d44513d9d",
          "md5": "dc734f75b2db64a01d827f870a3674f1"
        }
      ]
    }
  ]
}
