{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.2.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.2.0-alpha02.aar",
          "url": "savedstate-ktx-1.2.0-alpha02.aar",
          "size": 2524,
          "sha512": "4e9f4aed38cba0d1f6453d3ab7be2db248601701030956b3bc21ea93432d3f68ac58e8e55229e1e9ba205f90763b7d338f34bd805db23572a71d3b49758ea024",
          "sha256": "35441ff0d433b3f6ca559f2dbeab01f208b952f73100e42f268ba7245a34bb2b",
          "sha1": "208a6e0cd208f8e0adf5d1820ca9934dde728d1b",
          "md5": "89aa905b163c3850861eef3fb35e9880"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.2.0-alpha02.aar",
          "url": "savedstate-ktx-1.2.0-alpha02.aar",
          "size": 2524,
          "sha512": "4e9f4aed38cba0d1f6453d3ab7be2db248601701030956b3bc21ea93432d3f68ac58e8e55229e1e9ba205f90763b7d338f34bd805db23572a71d3b49758ea024",
          "sha256": "35441ff0d433b3f6ca559f2dbeab01f208b952f73100e42f268ba7245a34bb2b",
          "sha1": "208a6e0cd208f8e0adf5d1820ca9934dde728d1b",
          "md5": "89aa905b163c3850861eef3fb35e9880"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-ktx-1.2.0-alpha02-sources.jar",
          "url": "savedstate-ktx-1.2.0-alpha02-sources.jar",
          "size": 1138,
          "sha512": "0e900aadf8c3c8bd044d7dea887dcbe1bff9d359221d0c902320b9af83e453bacd9fabc6cfd5c3fd281e49909c1f168543ec7d997fd012f0537558e586cab8f9",
          "sha256": "c500d54f6588e4630bdef7729c62ca433a7662c93cc0551dfb5c63fad2c970be",
          "sha1": "9292f5a5bc3895f9759d7b6f30291743c1187698",
          "md5": "14f6da869d30af533ad728aed7faba45"
        }
      ]
    }
  ]
}
