{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.loader",
    "module": "loader",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "loader-1.2.0-alpha01.aar",
          "url": "loader-1.2.0-alpha01.aar",
          "size": 29939,
          "sha512": "51f4a6e51b57bd5a19bb5a068ee45630800c8571d6173fb9e2eba740d9d5a3798b8b031abfbb2760d3e0fb27c1a281b0788cc25b8a5eafa11b6bd9acbdb358c4",
          "sha256": "83d2bed2289acc861b2d2844eb3acff1cb5562ce22f375a7f3db2daff7d7fa70",
          "sha1": "68a437e0141f72ea39f78b011cdafc0e48a96f35",
          "md5": "9f4b99b95bdcae901e9313e2793e7208"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "loader-1.2.0-alpha01.aar",
          "url": "loader-1.2.0-alpha01.aar",
          "size": 29939,
          "sha512": "51f4a6e51b57bd5a19bb5a068ee45630800c8571d6173fb9e2eba740d9d5a3798b8b031abfbb2760d3e0fb27c1a281b0788cc25b8a5eafa11b6bd9acbdb358c4",
          "sha256": "83d2bed2289acc861b2d2844eb3acff1cb5562ce22f375a7f3db2daff7d7fa70",
          "sha1": "68a437e0141f72ea39f78b011cdafc0e48a96f35",
          "md5": "9f4b99b95bdcae901e9313e2793e7208"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "loader-1.2.0-alpha01-sources.jar",
          "url": "loader-1.2.0-alpha01-sources.jar",
          "size": 23891,
          "sha512": "3146c22297a7c884c9f41afa87e0925b938975153fed363cc06bfeb240edeef226441f17d829e6517b1559b17b6f2c10466fd7962e5aaddb32f8a02a567ceb73",
          "sha256": "0494774d078c4728cb635d0fb8d69b19c001ffd8a8dea31187ef0f6bf4192eaa",
          "sha1": "eda46dc05d968caccfd61030d210b9135bea4b31",
          "md5": "5cd19e0e47c809a983b955bd0926ffcf"
        }
      ]
    }
  ]
}
