{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha02"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.6.0-alpha02"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.6.0-alpha02.aar",
          "url": "appcompat-1.6.0-alpha02.aar",
          "size": 1157767,
          "sha512": "91576a8d45c173c38e0b67c2a1ed47ad63f466875725ec61371f5bc678efcd7b45735a573d52462b36b69f28df35d691ddd8504f29a2b16ba8f1b1ce26de7e10",
          "sha256": "ab8fbfdf9bce088b24c7cf48e8c59c3411fde997b03d32ed8db70fc9e9c364a6",
          "sha1": "c50b8f4480d63cceb810d1bc0ff735caa1f4ad01",
          "md5": "2132f0fef1ab24488d40d2b9b57b12f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha02"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.6.0-alpha02"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.6.0-alpha02.aar",
          "url": "appcompat-1.6.0-alpha02.aar",
          "size": 1157767,
          "sha512": "91576a8d45c173c38e0b67c2a1ed47ad63f466875725ec61371f5bc678efcd7b45735a573d52462b36b69f28df35d691ddd8504f29a2b16ba8f1b1ce26de7e10",
          "sha256": "ab8fbfdf9bce088b24c7cf48e8c59c3411fde997b03d32ed8db70fc9e9c364a6",
          "sha1": "c50b8f4480d63cceb810d1bc0ff735caa1f4ad01",
          "md5": "2132f0fef1ab24488d40d2b9b57b12f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-1.6.0-alpha02-sources.jar",
          "url": "appcompat-1.6.0-alpha02-sources.jar",
          "size": 490992,
          "sha512": "645cec3eee380e09c4d0fb2ad2abe364ea800f4a09416bce060fc8ec214201e0bc99213353e88fe767264b7399cb763f72bde1e4b06919df6ea8b5588a83dfd0",
          "sha256": "8e9dca5cc4c7b69db90e0c5437d221edd388620f64913b781222cee3fa9f5832",
          "sha1": "5c430454ca55196eaab20b4f98b01dae78adf567",
          "md5": "3ccc1dd4e73bcacb892d2dbc0d919626"
        }
      ]
    }
  ]
}
