{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha03.aar",
          "url": "lifecycle-service-2.5.0-alpha03.aar",
          "size": 4329,
          "sha512": "315cf6085a6063539a8be92dcaf5f99410d7c7ff1a600abece1c167bc698ac94736a1e73f025b379849346b8049904548614425713382cf5f6a414807115cda8",
          "sha256": "17ffa489fc262f20f8a376c85331ac09ad64dcf9ce113cb6bdc40d4992ce5c80",
          "sha1": "25b50bc74d31a93873511ecad864634d924fffc0",
          "md5": "b98a27e6908719758b589a7d3fa2ad24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha03.aar",
          "url": "lifecycle-service-2.5.0-alpha03.aar",
          "size": 4329,
          "sha512": "315cf6085a6063539a8be92dcaf5f99410d7c7ff1a600abece1c167bc698ac94736a1e73f025b379849346b8049904548614425713382cf5f6a414807115cda8",
          "sha256": "17ffa489fc262f20f8a376c85331ac09ad64dcf9ce113cb6bdc40d4992ce5c80",
          "sha1": "25b50bc74d31a93873511ecad864634d924fffc0",
          "md5": "b98a27e6908719758b589a7d3fa2ad24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-service-2.5.0-alpha03-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
