homepage: "https://etcd.io"
main_repo: "https://github.com/etcd-io/etcd"
primary_contact: "ptab@google.com"
auto_ccs :
  - "adam@adalogics.com"
language: go
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
