homepage: "https://opensource.apple.com/"
language: "c"
primary_contact: "nedwill@google.com"
main_repo: "https://github.com/googleprojectzero/SockFuzzer"
fuzzing_engines:
  - libfuzzer
  - honggfuzz
sanitizers:
  - address
