{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.4.0-beta01.aar",
          "url": "ui-test-1.4.0-beta01.aar",
          "size": 322624,
          "sha512": "0c798af46a18f187c49179b82e18a2cf71f762da92091bbcceb32cae8b523800b17af8d72e64dbef9751eb3899590cc53e86e8d87babf1ea9a436a7f2af889e2",
          "sha256": "8378923dd36ff9a464cd1f0dff38966942ce0b22ee782a3fb65367a14608457d",
          "sha1": "c42116db7fe296cdd339e375b6553b445bcb17f9",
          "md5": "7b2ad7bf6ae88cb0c6b16ece3d69ca50"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-1.4.0-beta01.aar",
          "url": "ui-test-1.4.0-beta01.aar",
          "size": 322624,
          "sha512": "0c798af46a18f187c49179b82e18a2cf71f762da92091bbcceb32cae8b523800b17af8d72e64dbef9751eb3899590cc53e86e8d87babf1ea9a436a7f2af889e2",
          "sha256": "8378923dd36ff9a464cd1f0dff38966942ce0b22ee782a3fb65367a14608457d",
          "sha1": "c42116db7fe296cdd339e375b6553b445bcb17f9",
          "md5": "7b2ad7bf6ae88cb0c6b16ece3d69ca50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-1.4.0-beta01-sources.jar",
          "url": "ui-test-1.4.0-beta01-sources.jar",
          "size": 101342,
          "sha512": "6b017f0697185d0f251a123550f2cfd00e85987d9ee9f2081dfd453eecf7d7dfb0e874f23cf1cca81cb555a21e581d932f56a062fad7ab2960898ffdea10146d",
          "sha256": "1fbcf36ec7683181e4023b12d358565ac2b32de46f45bb3a96229753f132bfa9",
          "sha1": "501ad44b673ac3e61c0d687f6e39e69fc0eb94ca",
          "md5": "3965a77d70c1d523ef3b923de03d8bfb"
        }
      ]
    }
  ]
}