[package]
name = "manager_service"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# bt deps
bt_common = { path = "../../common" }

# external deps
dbus = "0.9.2"
dbus-tokio = "0.7.3"
dbus-crossroads = "0.4.0"
dbus_projection = { path = "../dbus_projection" }
dbus_macros = { path = "../dbus_projection/dbus_macros" }
futures = "0.3.13"
inotify = "*"
log = "0.4.14"
nix = "*"
regex = "1.5"
serde_json = "1.0"
syslog = "4.0"
tokio = { version = "1.0", features = ["fs", "macros", "rt-multi-thread", "sync"] }

[build-dependencies]
pkg-config = "0.3.19"

[[bin]]
name = "btmanagerd"
build = "build.rs"
