{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha03.aar",
          "url": "activity-1.5.0-alpha03.aar",
          "size": 92516,
          "sha512": "5eff9b4ed439f24177c7b54888bd7f1e0652707139829d7867c78f260cbccc642e8e724a39c4188ffc5e233bbcc76ea0646ea99028b3b98ca92866822e94d870",
          "sha256": "08f29168be04f90a53ef3a3abd3cbc080110da0d2b8fec66769ec5e76d6f3945",
          "sha1": "26c2b75c6003513c2d8f731af697815f919e9e2b",
          "md5": "5b0f009807c069f7369a2183e3d6cc91"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.5.0-alpha03.aar",
          "url": "activity-1.5.0-alpha03.aar",
          "size": 92516,
          "sha512": "5eff9b4ed439f24177c7b54888bd7f1e0652707139829d7867c78f260cbccc642e8e724a39c4188ffc5e233bbcc76ea0646ea99028b3b98ca92866822e94d870",
          "sha256": "08f29168be04f90a53ef3a3abd3cbc080110da0d2b8fec66769ec5e76d6f3945",
          "sha1": "26c2b75c6003513c2d8f731af697815f919e9e2b",
          "md5": "5b0f009807c069f7369a2183e3d6cc91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.5.0-alpha03-sources.jar",
          "url": "activity-1.5.0-alpha03-sources.jar",
          "size": 39882,
          "sha512": "5bbc4be483800fe8c511d7a825c93680245cced0ae09ac6b28f02a9d1dce0cc5bcd5fc56855e4f8a982d085eb75cf486eb027522ccdff5d45e7f7a9d699b4936",
          "sha256": "aed2b7301cb9a94e9c340be6df927294969282db4f0e094b98d6ca9dfede8778",
          "sha1": "7ff0d8176dc874ddcc1015e27db0fe9697557935",
          "md5": "22ed71abec21c2f8b0ce0e514e63d233"
        }
      ]
    }
  ]
}
