{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-2.5.0-alpha03.aar",
          "size": 11431,
          "sha512": "fd8d0812d36e62aee102bbad82027976c242425a1dd59a9c2bc0d0a1d57415ec64a69827f674ffbe615bb2e937de81b78ea4473acf92192949fbaf03522dbedb",
          "sha256": "1cfabeb765ed6ba1e9c7a008197d7c693a4ceadbe5b1375e287e1286ec6b00ed",
          "sha1": "08f0b1da04f1aae0aa52436eb7ba65da7714cf66",
          "md5": "24719be1c0b0dc5444c10322f96ca1f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-2.5.0-alpha03.aar",
          "size": 11431,
          "sha512": "fd8d0812d36e62aee102bbad82027976c242425a1dd59a9c2bc0d0a1d57415ec64a69827f674ffbe615bb2e937de81b78ea4473acf92192949fbaf03522dbedb",
          "sha256": "1cfabeb765ed6ba1e9c7a008197d7c693a4ceadbe5b1375e287e1286ec6b00ed",
          "sha1": "08f0b1da04f1aae0aa52436eb7ba65da7714cf66",
          "md5": "24719be1c0b0dc5444c10322f96ca1f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-livedata-2.5.0-alpha03-sources.jar",
          "size": 6802,
          "sha512": "d1c94e8bdc39dedadffb69d21389b9069b2f0dea53d09f8453e6ce65d446bccf036b8fc8823539c3c2206d7d98b957d9891f7a8a602d1ddd9229559bf5f96617",
          "sha256": "44ee4777d199807c679608ae677d4e6ed31a57c4c6bc9a342c36252ca597c9ae",
          "sha1": "79c9b6bb8cb5d788988ae6a481f29c6692c3bdd2",
          "md5": "395b96cd40d8b538beae4edfc293d1b2"
        }
      ]
    }
  ]
}
