dtb-$(CONFIG_SOC_GS201) += \
        gs201-b0.dtb \
        gs201-b0_v2-ipop.dtb \

dtbo-y += \
        gs201-tangorpro-dev2.dtbo \
        gs201-tangorpro-evt2.dtbo \
        gs201-tangorpro-evt2-bezelblack.dtbo \
        gs201-tangorpro-evt2-wingboard.dtbo \
        gs201-tangorpro-dvt1.dtbo \
        gs201-tangorpro-pvt1.dtbo \
        gs201-tangorpro-mp.dtbo

gs201-tangorpro-dev2.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-tangorpro-evt2.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-tangorpro-evt2-bezelblack.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-tangorpro-evt2-wingboard.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-tangorpro-dvt1.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-tangorpro-pvt1.dtbo-base := google-base/gs201-b0_v2-ipop.dtb
gs201-tangorpro-mp.dtbo-base := google-base/gs201-b0_v2-ipop.dtb

MKDTIMG_FLAGS += --page_size=4096  --id=/:board_id --rev=/:board_rev
