{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.0-alpha03.aar",
          "url": "navigation-runtime-ktx-2.5.0-alpha03.aar",
          "size": 1778,
          "sha512": "fe482e1a49204c6e36110ebdf1b50fc5e068bcbcce6c69d36ce18f98e786b62d3a514dbed47287bf0054d2a019f4be9c6dd8a6fd7bb159ea63551ea06fdb7698",
          "sha256": "b39f0c720246dcf2fb3ebeaa44ed4a49feb85156d2e472938ed12091f47977d6",
          "sha1": "24dd9def1e7d714847ef945eabdb4f665e7505e2",
          "md5": "a6616d36f293d7296cb46c7f818f6d24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.0-alpha03.aar",
          "url": "navigation-runtime-ktx-2.5.0-alpha03.aar",
          "size": 1778,
          "sha512": "fe482e1a49204c6e36110ebdf1b50fc5e068bcbcce6c69d36ce18f98e786b62d3a514dbed47287bf0054d2a019f4be9c6dd8a6fd7bb159ea63551ea06fdb7698",
          "sha256": "b39f0c720246dcf2fb3ebeaa44ed4a49feb85156d2e472938ed12091f47977d6",
          "sha1": "24dd9def1e7d714847ef945eabdb4f665e7505e2",
          "md5": "a6616d36f293d7296cb46c7f818f6d24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.5.0-alpha03-sources.jar",
          "url": "navigation-runtime-ktx-2.5.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
