{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-animation-testing",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-testing-1.0.0-alpha03.aar",
          "url": "core-animation-testing-1.0.0-alpha03.aar",
          "size": 4415,
          "sha512": "bc9ecfce6800536b9d6ace37e492595c374fa77be7c7b65b0fd0c826033db5af7bd638140096d943298dd01278218404b24b05849129b730a524979701bf873d",
          "sha256": "22e51253c263c031c674575bd297c6d794d544a60010701f2e67ee4f134c5d17",
          "sha1": "8b1740d2f12adf5d8b959dc0070f9c3c1b93c6de",
          "md5": "c0625c141aeca1e68dabe567a1a6d49b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-animation",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-testing-1.0.0-alpha03.aar",
          "url": "core-animation-testing-1.0.0-alpha03.aar",
          "size": 4415,
          "sha512": "bc9ecfce6800536b9d6ace37e492595c374fa77be7c7b65b0fd0c826033db5af7bd638140096d943298dd01278218404b24b05849129b730a524979701bf873d",
          "sha256": "22e51253c263c031c674575bd297c6d794d544a60010701f2e67ee4f134c5d17",
          "sha1": "8b1740d2f12adf5d8b959dc0070f9c3c1b93c6de",
          "md5": "c0625c141aeca1e68dabe567a1a6d49b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-animation-testing-1.0.0-alpha03-sources.jar",
          "url": "core-animation-testing-1.0.0-alpha03-sources.jar",
          "size": 2454,
          "sha512": "7fe420be5d8a30f06b34f3b4ee193388a92913a2bbe6620801a91f6f7693e1c89eff439a6366a6738f07b0c522a634c14dde95ec4b49cb51abc485ef6b9adcb8",
          "sha256": "7ae1539e05ab249054d133171f41268650e5d15fc892d5ce695e6b924495ad6c",
          "sha1": "5a9afdf56f0852a642122734d719d59a26982fcc",
          "md5": "ecd24824ee48feb72c14f189a1a46b99"
        }
      ]
    }
  ]
}