homepage: "https://developers.google.com/protocol-buffers/"
language: jvm
primary_contact: "kfm@google.com"
auto_ccs:
  - "meumertzheim@code-intelligence.com"
  - "acozzette@google.com"
  - "elharo@google.com"
  - "pzd@google.com"
  - "sandyzhang@google.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/protocolbuffers/protobuf"
sanitizers:
  - address
