{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-samples",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.1.0-beta01.aar",
          "url": "window-1.1.0-beta01.aar",
          "size": 310291,
          "sha512": "189f0fa5a338d098fe86c1ce8a9799dfaa5618c870bfa055a85e8d0bce04bd2316a075621369f9628704bfd90ae158a5acb97944b2cf7d8fe52f7a5ec705dc40",
          "sha256": "b90445854a7ca24789d160fca0b63a753287df1766301c5c8ad244fc7ca4c4d2",
          "sha1": "485dc12746284d0f98619ea6216a5cbd902a9eb5",
          "md5": "ea81da7d6481d26cff8aee120dd6825c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-samples",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.1.0-beta01.aar",
          "url": "window-1.1.0-beta01.aar",
          "size": 310291,
          "sha512": "189f0fa5a338d098fe86c1ce8a9799dfaa5618c870bfa055a85e8d0bce04bd2316a075621369f9628704bfd90ae158a5acb97944b2cf7d8fe52f7a5ec705dc40",
          "sha256": "b90445854a7ca24789d160fca0b63a753287df1766301c5c8ad244fc7ca4c4d2",
          "sha1": "485dc12746284d0f98619ea6216a5cbd902a9eb5",
          "md5": "ea81da7d6481d26cff8aee120dd6825c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-samples",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.1.0-beta01"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.1.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.1.0-beta01-sources.jar",
          "url": "window-1.1.0-beta01-sources.jar",
          "size": 122008,
          "sha512": "8e85ae6efe64b04c0a99b868c2729cb743af50c799ef13566b39ed759fbfbd86669bd326a5ba889d286785e3f7bc236d6c09d9b0d6e9cb6ba0fddd8a0479aca2",
          "sha256": "7b52dbc3d4510bcb29b773a01d446160fbeaf2a38ad438e39b54adb4fc039a7a",
          "sha1": "740efa157ef931b52b6653651f66afee20131aab",
          "md5": "c4b5c8b55a5187a390248146e3e9dbad"
        }
      ]
    }
  ]
}