{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.5.0-alpha03.aar",
          "url": "navigation-fragment-ktx-2.5.0-alpha03.aar",
          "size": 1786,
          "sha512": "12664720f6796e9e3676d323d360834f9684ad1290392347af77f1ea82250b03b51bbb0e75a6cb2af41b54f419fa88b23185a1509acfff5d73500ffee153c93c",
          "sha256": "61572f61d882a16ecfb5181e4476edd6e5edee43f9e89ad78a99fc0242f6c431",
          "sha1": "3c116ed66e98358f0d283130e624c5524a017ef5",
          "md5": "fab2c7d7d38b725abb2c692d6f519bfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.5.0-alpha03.aar",
          "url": "navigation-fragment-ktx-2.5.0-alpha03.aar",
          "size": 1786,
          "sha512": "12664720f6796e9e3676d323d360834f9684ad1290392347af77f1ea82250b03b51bbb0e75a6cb2af41b54f419fa88b23185a1509acfff5d73500ffee153c93c",
          "sha256": "61572f61d882a16ecfb5181e4476edd6e5edee43f9e89ad78a99fc0242f6c431",
          "sha1": "3c116ed66e98358f0d283130e624c5524a017ef5",
          "md5": "fab2c7d7d38b725abb2c692d6f519bfa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-ktx-2.5.0-alpha03-sources.jar",
          "url": "navigation-fragment-ktx-2.5.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
