homepage: "https://github.com/google/zopfli"
language: c++
primary_contact: "lode@google.com"
sanitizers:
  - address
# Disabled MSAN because of https://github.com/google/oss-fuzz/issues/6294
#  - memory
  - undefined
main_repo: 'https://github.com/google/zopfli'