homepage: "https://duckdb.org/"
language: c++
primary_contact: "quack@duckdb.org"
main_repo: "https://github.com/duckdb/duckdb/"
auto_ccs: 
  - "hannes.muehleisen@gmail.com"
  - "david@adalogics.com"
