{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout",
    "version": "2.2.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.0-alpha05.aar",
          "url": "constraintlayout-2.2.0-alpha05.aar",
          "size": 480057,
          "sha512": "c8a98985b3a1f062bd56de5687ad0e1261944a0bbed6d5b3060d17a31748911fbe0a565e5b6394d9f751069b963d1732e0ed5a684f9c7ea523c0c76689445d12",
          "sha256": "3ef90b588f1f36b835e64dcffb7d4e031146c2e0143b168182b7a6c52157abe4",
          "sha1": "f4b539b0bc162a9e62bb669d033f3d26cec95cec",
          "md5": "79dce25af5aa28a588b1816dbdd555ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-2.2.0-alpha05.aar",
          "url": "constraintlayout-2.2.0-alpha05.aar",
          "size": 480057,
          "sha512": "c8a98985b3a1f062bd56de5687ad0e1261944a0bbed6d5b3060d17a31748911fbe0a565e5b6394d9f751069b963d1732e0ed5a684f9c7ea523c0c76689445d12",
          "sha256": "3ef90b588f1f36b835e64dcffb7d4e031146c2e0143b168182b7a6c52157abe4",
          "sha1": "f4b539b0bc162a9e62bb669d033f3d26cec95cec",
          "md5": "79dce25af5aa28a588b1816dbdd555ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-2.2.0-alpha05-sources.jar",
          "url": "constraintlayout-2.2.0-alpha05-sources.jar",
          "size": 292913,
          "sha512": "5d1745bb42023045421a6a897ae8ba281e5b8fcb29b870a39587b3cd8f958609f023fb8dfc166dcb7532d0de7c6497b4b37167b86cdfd3b8bfdb0b5b473a0fd1",
          "sha256": "3303a26e4a58e6fdd3dd3000fdd16c10506256f2c2db3e70d3899a07bc8c61d6",
          "sha1": "58e6e0f115546ebccde38f7d39bf2e288e5fd10a",
          "md5": "ae3361fed5eec06748cab578d7de8beb"
        }
      ]
    }
  ]
}