# Define the building environment
language: c

# Use Travis-CI Ubuntu 18.04 Bionic Beaver, "full image" variant
sudo: required
dist: bionic

script:
  - FEDORA_MAJOR=33 FEDORA_MINOR=1.2 scripts/ci/travis-kvm-setup.sh

# Do not spam by email so long as the build succeeds
notifications:
  email:
    on_success: never
