{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.interpolator",
    "module": "interpolator",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 8647,
          "sha512": "671156d5b4a14e5984455271d277f5f58b3d0256a128049a10ebfb967dec2dde4a01559583ba73d4e894acd103090d01e856c4313ba312ad945b2e1a68919ecb",
          "sha256": "cc23b7f0733d1e829994bfe0a89e736e56f250c060bf0b9946a24b29439d357d",
          "sha1": "e356915be3b12d3991da08d8becf18b5d4ca4a2f",
          "md5": "0fdfccd16d117e9f8d9447a1858025bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 8647,
          "sha512": "671156d5b4a14e5984455271d277f5f58b3d0256a128049a10ebfb967dec2dde4a01559583ba73d4e894acd103090d01e856c4313ba312ad945b2e1a68919ecb",
          "sha256": "cc23b7f0733d1e829994bfe0a89e736e56f250c060bf0b9946a24b29439d357d",
          "sha1": "e356915be3b12d3991da08d8becf18b5d4ca4a2f",
          "md5": "0fdfccd16d117e9f8d9447a1858025bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01-sources.jar",
          "url": "interpolator-1.1.0-alpha01-sources.jar",
          "size": 6822,
          "sha512": "0bb7f6e999ad3f79ab6379b77ec8bf5f94013805109acafa4f2d5b2bed336f4a328986415686b274cfb6999cd93d6a5a3cf9da216e3edcae8bf31913c396828d",
          "sha256": "b424610869ff191adbc3fd5a3f978accd3de9aa4464032dd99b0f57eb8248a83",
          "sha1": "87c4b919f0886d09bd85d4626cadc9e08ef160af",
          "md5": "69943d660297c81234b76ece84a5db73"
        }
      ]
    }
  ]
}
