homepage: "https://android.googlesource.com/platform/external/libldac"
language: c++
primary_contact: "Chisato.Kenmochi@sony.com"
auto_ccs:
  - twsmith@mozilla.com
vendor_ccs:
  - bcreasey@google.com
  - hamzeh@google.com
  - geuteneier@google.com
  - maverickm@google.com
  - warrenwright@google.com
  - ailport@google.com
  - kimtony@google.com
  - faerber@google.com
  - greendonald@google.com
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
  - dataflow
sanitizers:
  - address
  - dataflow
main_repo: 'https://android.googlesource.com/platform/external/libldac'
