{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-appcompat",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 4875,
          "sha512": "1e8e59f3b301b5aebb6ca4bc3a70f6bcccf8bed87a940b5df9c48c03e7769b19e73364b4355b8100ac74ea0930b49e52a06ed4d36cf94f1d605db499489cc4e8",
          "sha256": "78c6e8538180e2836c9ed37e44f1627a70de79b5eac69455fc504b800215a097",
          "sha1": "64f25119220302f89e25fd4cd497f5cb3da7afd9",
          "md5": "fbdb0dcb55078b25de7b9cb4000fa5d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 4875,
          "sha512": "1e8e59f3b301b5aebb6ca4bc3a70f6bcccf8bed87a940b5df9c48c03e7769b19e73364b4355b8100ac74ea0930b49e52a06ed4d36cf94f1d605db499489cc4e8",
          "sha256": "78c6e8538180e2836c9ed37e44f1627a70de79b5eac69455fc504b800215a097",
          "sha1": "64f25119220302f89e25fd4cd497f5cb3da7afd9",
          "md5": "fbdb0dcb55078b25de7b9cb4000fa5d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "url": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "size": 4355,
          "sha512": "05730b58fb8391f28050b8cc51cfb42fdfc6c888cbb70b642d1e8b11f82b15946b65f05350de21d4f222e58f2e2d97ed4e195facd843c06552b784e7c4edd8ec",
          "sha256": "8c37ea1aefdd5d8e36d6fd5d7535c6fdfadd02b61fa51c1e4178b0cec49e6de0",
          "sha1": "6100352f9c99794e5ec330e4e428e344a7b3a245",
          "md5": "d708308a2084b09201efe840d9541b78"
        }
      ]
    }
  ]
}
