{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.cardview",
    "module": "cardview",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cardview-1.1.0-alpha01.aar",
          "url": "cardview-1.1.0-alpha01.aar",
          "size": 22789,
          "sha512": "f648f9a30a68be5ca41b83fe5a66486d014244f8f23d8c4de592f926a8802d8e5291dcc76149191d40764e421d4c8b23d6630a7c716f89670eb2fc6d14e8e27e",
          "sha256": "09cabfcb338cb31f626be127014d8b9df40871c56f48a403dd8e89e85c3c4343",
          "sha1": "e8600c492b33d63705e68aa3cb7a8b4530adce86",
          "md5": "c376d91ea3bd904bc3d0ddd33a69d2c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cardview-1.1.0-alpha01.aar",
          "url": "cardview-1.1.0-alpha01.aar",
          "size": 22789,
          "sha512": "f648f9a30a68be5ca41b83fe5a66486d014244f8f23d8c4de592f926a8802d8e5291dcc76149191d40764e421d4c8b23d6630a7c716f89670eb2fc6d14e8e27e",
          "sha256": "09cabfcb338cb31f626be127014d8b9df40871c56f48a403dd8e89e85c3c4343",
          "sha1": "e8600c492b33d63705e68aa3cb7a8b4530adce86",
          "md5": "c376d91ea3bd904bc3d0ddd33a69d2c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cardview-1.1.0-alpha01-sources.jar",
          "url": "cardview-1.1.0-alpha01-sources.jar",
          "size": 16510,
          "sha512": "10f4f42e55922d01073e5b8ecfbaf70847e8662a8e214b49e468d5cf0156faf389a3b933969f51c4d62d4de2faf00c4826c492aaaeee9c54f0af205bdb217b18",
          "sha256": "1e63af91477f0f738c4e1b72a63e52c09737fca4ec91190645b3ace6787e0da2",
          "sha1": "a2f300361bb55705c74987c26471ed63aec851a7",
          "md5": "791bb9de8f4314c718e5218a05230b3c"
        }
      ]
    }
  ]
}
