homepage: "https://www.sqlalchemy.org"
language: python
primary_contact: "mike_mp@zzzcomputing.com"
auto_ccs:
  - "Adam@adalogics.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "ihttps://github.com/sqlalchemy/sqlalchemy"
