{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "collection-1.3.0-alpha01.jar",
          "url": "collection-1.3.0-alpha01.jar",
          "size": 40384,
          "sha512": "bd9c6591a4dfb61c5db045b339acffc65e3d10a6c08532ec8438510775fac8b660c7f541e0e75a7b5449e3479bd29af77018f3d3f2f104615cd1493e650116d3",
          "sha256": "16d77e8c443fa55fe9a6074d00445d520ca5c9f913cefdbf4828356255214e42",
          "sha1": "34dbc21d203cc4d4d623ac572a21acd4ccd716af",
          "md5": "a56a8f491ab2f61ef5145a139097b0e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "collection-1.3.0-alpha01.jar",
          "url": "collection-1.3.0-alpha01.jar",
          "size": 40384,
          "sha512": "bd9c6591a4dfb61c5db045b339acffc65e3d10a6c08532ec8438510775fac8b660c7f541e0e75a7b5449e3479bd29af77018f3d3f2f104615cd1493e650116d3",
          "sha256": "16d77e8c443fa55fe9a6074d00445d520ca5c9f913cefdbf4828356255214e42",
          "sha1": "34dbc21d203cc4d4d623ac572a21acd4ccd716af",
          "md5": "a56a8f491ab2f61ef5145a139097b0e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "collection-1.3.0-alpha01-sources.jar",
          "url": "collection-1.3.0-alpha01-sources.jar",
          "size": 36086,
          "sha512": "98b7e5ad599699a84126eeac45de6690399036941b14fbf9da83a51c160d2563d925377e872faf1ebb1837d925d1b72012b41a7997d341b61b370a3f3c5e0680",
          "sha256": "2d9f17d27aa8cf3c32bfe0cbe253d242a28d91934e2c9df0d48eb9be63c03641",
          "sha1": "99c1c9185cfa075be7604ce433ea0402537ee723",
          "md5": "052d3548306f5322b7411c1feb7fd4de"
        }
      ]
    }
  ]
}
