{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.1.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.1.0-alpha06.aar",
          "url": "material3-1.1.0-alpha06.aar",
          "size": 3774010,
          "sha512": "354cbee1b17d05df432bf7fe848535ba84883f2cad64ff2009a0a4ca92de1af99e33a793f78d895b2ec480b9d25cd999e6a42af85afb11ccba2e35c7153f3b45",
          "sha256": "07eaea15a21864be014fe45b500b705acce7cecaa6a3117f0d17949b182c2dbd",
          "sha1": "f9730daa05ee8f6b483d4dead2a8708d2d3e26de",
          "md5": "9587306e2b2e44a7af7da26674d04d24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "material3-1.1.0-alpha06.aar",
          "url": "material3-1.1.0-alpha06.aar",
          "size": 3774010,
          "sha512": "354cbee1b17d05df432bf7fe848535ba84883f2cad64ff2009a0a4ca92de1af99e33a793f78d895b2ec480b9d25cd999e6a42af85afb11ccba2e35c7153f3b45",
          "sha256": "07eaea15a21864be014fe45b500b705acce7cecaa6a3117f0d17949b182c2dbd",
          "sha1": "f9730daa05ee8f6b483d4dead2a8708d2d3e26de",
          "md5": "9587306e2b2e44a7af7da26674d04d24"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material3-1.1.0-alpha06-sources.jar",
          "url": "material3-1.1.0-alpha06-sources.jar",
          "size": 350351,
          "sha512": "901d7cde42592d1475fe5fe3890d4db65c4bbb87d24370e347d809e8a947f4d5f22f389be138ae42e1dfe3c6aa95794d32c1cb5683b6bf4bba1e3ae3b19669e3",
          "sha256": "28c6746fcc26acdf6b7b9971c235117714e088664b3d0f39b029e460b570cae1",
          "sha1": "e9be4ecc0a84bebd8677b5c6762966922e7139c9",
          "md5": "e5a17f1a59568708148288ef65a7b6f7"
        }
      ]
    }
  ]
}