{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-livedata",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.4.0-beta01.aar",
          "url": "runtime-livedata-1.4.0-beta01.aar",
          "size": 8228,
          "sha512": "eeeb4e619fb795a75968c0c02349a6c95b70682a2628ba5709a20544bb1cc6abfaa4c0913ea7bca920568826553f1acc591e0e0f24405bd89278cacb40ba020e",
          "sha256": "e4b367b9d13eaadc21d0b96cb94498e298829312025892dff5fcae0440b5778f",
          "sha1": "14d7780519efe3bf7e211651678a76eb42bd3eb5",
          "md5": "a6bd8581f6bdab3897ad279fe36e63c3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-livedata-1.4.0-beta01.aar",
          "url": "runtime-livedata-1.4.0-beta01.aar",
          "size": 8228,
          "sha512": "eeeb4e619fb795a75968c0c02349a6c95b70682a2628ba5709a20544bb1cc6abfaa4c0913ea7bca920568826553f1acc591e0e0f24405bd89278cacb40ba020e",
          "sha256": "e4b367b9d13eaadc21d0b96cb94498e298829312025892dff5fcae0440b5778f",
          "sha1": "14d7780519efe3bf7e211651678a76eb42bd3eb5",
          "md5": "a6bd8581f6bdab3897ad279fe36e63c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runtime-livedata-1.4.0-beta01-sources.jar",
          "url": "runtime-livedata-1.4.0-beta01-sources.jar",
          "size": 1824,
          "sha512": "f99b82e6ff8187d8755043f5ae6407b6e6bf334cd87b08c70dc9dbd132be75f6a143b2faa979bb99fccd500abd12a386e33cfb753c2103475bf233ec04898cad",
          "sha256": "da87bca8c139f251c2d436db527fea015f25827fc4855a4665ded4bb90214835",
          "sha1": "f7720a035af5da10fbaf0454b0c0ae2ad41f43be",
          "md5": "4935aa912df821d2c03e8a99dd929d22"
        }
      ]
    }
  ]
}