{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.5.0-alpha01.jar",
          "url": "room-compiler-processing-2.5.0-alpha01.jar",
          "size": 889095,
          "sha512": "436eb64169eeec08d5b202791f9a17b9cf2193d6c882ebd7380856350ecd932b3cc85552d6984674b53c10adaa990001b7762c154e7c0b48f656fbb23dce4188",
          "sha256": "1358560c54b9651392cadef3a0f8cb7afb3d2d43d6691440ff443fca3c449f81",
          "sha1": "a08b66607b01731c3622962911e0aefd171afcf4",
          "md5": "ab6167c16a2c5ba5af8ecba8fd0abc61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.11"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.6.10-1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.5.0-alpha01.jar",
          "url": "room-compiler-processing-2.5.0-alpha01.jar",
          "size": 889095,
          "sha512": "436eb64169eeec08d5b202791f9a17b9cf2193d6c882ebd7380856350ecd932b3cc85552d6984674b53c10adaa990001b7762c154e7c0b48f656fbb23dce4188",
          "sha256": "1358560c54b9651392cadef3a0f8cb7afb3d2d43d6691440ff443fca3c449f81",
          "sha1": "a08b66607b01731c3622962911e0aefd171afcf4",
          "md5": "ab6167c16a2c5ba5af8ecba8fd0abc61"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.5.0-alpha01-sources.jar",
          "url": "room-compiler-processing-2.5.0-alpha01-sources.jar",
          "size": 186420,
          "sha512": "e84add61504925ead33963d45317ed14a79be5b427742d7eb9ebb4402890047d5da4cc6d46497ce95a18f5449820ef697e930f8f5195bc05f96fc02c4b6c8512",
          "sha256": "b544bea764f2d6e16d79dd81ce28e188ef14c8dc963659681183249d19f88c44",
          "sha1": "51e67aedc12e8f00c45b9418faa30a0bfe327af2",
          "md5": "2d0dbe6e5136db6c65dbdcba57adcbae"
        }
      ]
    }
  ]
}
