{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.2.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha05.aar",
          "url": "biometric-1.2.0-alpha05.aar",
          "size": 241146,
          "sha512": "066b9a69d7eaeab425e5fd62c269905326e4a6514334f7e6d372e66336dcc9e471904d2b46d60e6e2051bd1f55c08a6c33d1250a789caf320787b3d63767bb52",
          "sha256": "4ee2f93d4d7ca443ca58c605e62ee4aa9d2d49ac7b5513a0a71d04f4d4e1e685",
          "sha1": "780080285df84ba8dc8490c1d7729f01615d23ef",
          "md5": "20a26ef31e00ff11bef4c1417faaf1e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.2.0-alpha05.aar",
          "url": "biometric-1.2.0-alpha05.aar",
          "size": 241146,
          "sha512": "066b9a69d7eaeab425e5fd62c269905326e4a6514334f7e6d372e66336dcc9e471904d2b46d60e6e2051bd1f55c08a6c33d1250a789caf320787b3d63767bb52",
          "sha256": "4ee2f93d4d7ca443ca58c605e62ee4aa9d2d49ac7b5513a0a71d04f4d4e1e685",
          "sha1": "780080285df84ba8dc8490c1d7729f01615d23ef",
          "md5": "20a26ef31e00ff11bef4c1417faaf1e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.2.0-alpha05-sources.jar",
          "url": "biometric-1.2.0-alpha05-sources.jar",
          "size": 70077,
          "sha512": "2b66765b52873dd268614ad33ad248f45d5af19662c8b0fbf90ba1aa8e5dc1b817afb030dafadff826dccc51d961663a7b026c8b4a830b65091ebe2eb31c5b9d",
          "sha256": "fbacc822f8ae920b9fb3709bef885d615d5bb8bffa64279a71d2b5a98c6a0d0d",
          "sha1": "41c521e443c7c0b585c9140b3acac57a6bf4fa11",
          "md5": "e859f2400a71a31d6b7cb01bb83c18b0"
        }
      ]
    }
  ]
}
