homepage: "https://github.com/supranational/blst"
language: c++
primary_contact: "guidovranken@gmail.com"
main_repo: "https://github.com/supranational/blst.git"
sanitizers:
 - address
 - undefined
# Disabled MSAN because of https://github.com/google/oss-fuzz/issues/6294
#  - memory
architectures:
 - x86_64
 - i386
auto_ccs:
 - "kelly@supranational.net"
 - "diederik.loerakker@ethereum.org"
 - "hoffmang@chia.net"
 - "bram@chia.net"
 - "mariano@chia.net"
 - "arvid@chia.net"
 - "bill@chia.net"
