{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-junit4",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.4.0-beta01.aar",
          "url": "ui-test-junit4-1.4.0-beta01.aar",
          "size": 156700,
          "sha512": "3c64b29aeb8b17345eec25b125aeb8e7e2207d21640613f4378ab1a7dcb184bdc8fae20805812ebd257cb17f03d67e1b27b4c4fc379ae8a07d2e781c02d53908",
          "sha256": "e73c22026ee0b2f44d1075c3ae351b2c310686daf2cab343b1eea18665ff1fb9",
          "sha1": "1f80c9d633c1eadbe9b6f0f896bc01598c88c7f9",
          "md5": "f6eaaebb5b7cc9c41f7afd7769e2ff64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "monitor",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-core",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-idling-resource",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-junit4-1.4.0-beta01.aar",
          "url": "ui-test-junit4-1.4.0-beta01.aar",
          "size": 156700,
          "sha512": "3c64b29aeb8b17345eec25b125aeb8e7e2207d21640613f4378ab1a7dcb184bdc8fae20805812ebd257cb17f03d67e1b27b4c4fc379ae8a07d2e781c02d53908",
          "sha256": "e73c22026ee0b2f44d1075c3ae351b2c310686daf2cab343b1eea18665ff1fb9",
          "sha1": "1f80c9d633c1eadbe9b6f0f896bc01598c88c7f9",
          "md5": "f6eaaebb5b7cc9c41f7afd7769e2ff64"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-junit4-1.4.0-beta01-sources.jar",
          "url": "ui-test-junit4-1.4.0-beta01-sources.jar",
          "size": 43673,
          "sha512": "350d842928aa17e1d922fe4733c734fd0a575a133e534733923dac36ef80d4af5d878b7b1299e6b75f73b79ad31c5acd33da00c8c30ea8fbe803088c12ea9710",
          "sha256": "fe4328f20d512888daf46628c0de426444878325bca2325f6237ea33e5790b6c",
          "sha1": "8957b06775c742b0a3e55d9c23cf511aa1f7b617",
          "md5": "62602564d0e322f2d75bdd48e90cb684"
        }
      ]
    }
  ]
}