{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.4.0-beta01.aar",
          "url": "material-icons-core-1.4.0-beta01.aar",
          "size": 719787,
          "sha512": "f72f7bc6868e9b020195a45897811800d3894079685814488f50f53aabd9af8c214c3283c9850bbf83881f425108df3d498d8e60ed65369b3f6cb079063792bf",
          "sha256": "8fd9498599db6efd4afba50b7df9a7beb137e4315d2abd75d06f7470350fc8b8",
          "sha1": "a2aadded0fdc4fd650850153e0c60210eddbbe69",
          "md5": "2b35e25cba8e268d8072f372d42cc6b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.4.0-beta01.aar",
          "url": "material-icons-core-1.4.0-beta01.aar",
          "size": 719787,
          "sha512": "f72f7bc6868e9b020195a45897811800d3894079685814488f50f53aabd9af8c214c3283c9850bbf83881f425108df3d498d8e60ed65369b3f6cb079063792bf",
          "sha256": "8fd9498599db6efd4afba50b7df9a7beb137e4315d2abd75d06f7470350fc8b8",
          "sha1": "a2aadded0fdc4fd650850153e0c60210eddbbe69",
          "md5": "2b35e25cba8e268d8072f372d42cc6b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-1.4.0-beta01-sources.jar",
          "url": "material-icons-core-1.4.0-beta01-sources.jar",
          "size": 239777,
          "sha512": "ee8456ea6c8b64c8da7eefb09c9ee1e2fa22353863e0fb5780b1696c8c31c45740545a64e2034802321f186c681d554187c2e1b966b9f565ee4e40589c2bd51f",
          "sha256": "34fd248de9709c4828d350369f7e8b0dac7113ac6b215539c43264b828092010",
          "sha1": "fdfdd86bb6169696ee17beda93e5976830627051",
          "md5": "bbbd186b4ebf8ffdb000d83161522a7a"
        }
      ]
    }
  ]
}