{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.palette",
    "module": "palette",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "palette-1.1.0-alpha01.aar",
          "url": "palette-1.1.0-alpha01.aar",
          "size": 22395,
          "sha512": "0d267270259ab4842b5bd973c9c50d683494fab492993db1f99c596670df5749656f08ea306bf0cb61d8b7c496ffb4a8dd7b987bc7409b9c4cce76c2d2c3c1ba",
          "sha256": "1a315ec9d836e9e6976b546b04533a2e43e29c7c1af246a20a6baf6026ce7c02",
          "sha1": "7d1d54559876572a900e995d8e814be4c477c8ad",
          "md5": "d48cd815b96fcdc9e19bbc74c7cb03f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "palette-1.1.0-alpha01.aar",
          "url": "palette-1.1.0-alpha01.aar",
          "size": 22395,
          "sha512": "0d267270259ab4842b5bd973c9c50d683494fab492993db1f99c596670df5749656f08ea306bf0cb61d8b7c496ffb4a8dd7b987bc7409b9c4cce76c2d2c3c1ba",
          "sha256": "1a315ec9d836e9e6976b546b04533a2e43e29c7c1af246a20a6baf6026ce7c02",
          "sha1": "7d1d54559876572a900e995d8e814be4c477c8ad",
          "md5": "d48cd815b96fcdc9e19bbc74c7cb03f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palette-1.1.0-alpha01-sources.jar",
          "url": "palette-1.1.0-alpha01-sources.jar",
          "size": 16321,
          "sha512": "ac48aea2d3972bf093254e24264b0ae7c26c66b050a8b9c38271b0d47912ab576692259a25b39359558851d5dd66719a4861a5c90c7756559cba0000e927adb1",
          "sha256": "740aa0d384175a5179c7a252063b78d58c74df5e21352a8722faedfa733c4597",
          "sha1": "a230912fd471a25be7633a7e6cd9b167fb1ff6c3",
          "md5": "64942ef2bdec6d0b64e929805abad314"
        }
      ]
    }
  ]
}
