{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.arch.core",
    "module": "core-common",
    "version": "2.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-common-2.2.0-alpha01.jar",
          "url": "core-common-2.2.0-alpha01.jar",
          "size": 11428,
          "sha512": "15a47a74d4222758715c13be815cc14957550db24d11ed48bbb0c9c61c0baac79a177c21a980c9460fc40516d14c17913aa1aa2d21dc46182bc02185fa661a87",
          "sha256": "bddb7e03be1de4031c3e2ba8756d02462fc8d5af9fdcbd1f106f5ff16b1cad45",
          "sha1": "d7122fd25e6dd910a9346cdc357b0b9209dff4c0",
          "md5": "017c9b3e84e30e4b5428ab05819bd93f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-common-2.2.0-alpha01.jar",
          "url": "core-common-2.2.0-alpha01.jar",
          "size": 11428,
          "sha512": "15a47a74d4222758715c13be815cc14957550db24d11ed48bbb0c9c61c0baac79a177c21a980c9460fc40516d14c17913aa1aa2d21dc46182bc02185fa661a87",
          "sha256": "bddb7e03be1de4031c3e2ba8756d02462fc8d5af9fdcbd1f106f5ff16b1cad45",
          "sha1": "d7122fd25e6dd910a9346cdc357b0b9209dff4c0",
          "md5": "017c9b3e84e30e4b5428ab05819bd93f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-common-2.2.0-alpha01-sources.jar",
          "url": "core-common-2.2.0-alpha01-sources.jar",
          "size": 5618,
          "sha512": "f955f8e10858f7a13a6ed433029a511544a207776c9beeecb8d33550171e474ab91d52444ee2d32fb2ed15af7eb48012233c7b0ceecc6f2bcba8ca6d86d0d545",
          "sha256": "44fe3e9a965aaa2ad85d81d7a1f0911fd4ede29d1f2079da8858d304c5d880e6",
          "sha1": "57706d8518dbfa2a664c770dda9285e6950680fd",
          "md5": "e957ed668e3b4cbb2a188d14bf0e3342"
        }
      ]
    }
  ]
}
