{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.4.0-beta01.aar",
          "url": "material-1.4.0-beta01.aar",
          "size": 2790226,
          "sha512": "897b94ca528cefa1f6ccff9e8061e613918570285e78dcc186d6a615f2f220352fb5cc082086176bc17a30890c22e273a09168b3197f3170cab267ef0d8f8b96",
          "sha256": "2c16e9b77263d6f0c21b3934e7151c05c61ccef123ebc244be0bd4e0bdae67b1",
          "sha1": "42ece0e7c19eb92509a4445df791df73e306966c",
          "md5": "163bd891c0891bed580e3c5f90b2391e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.4.0-beta01.aar",
          "url": "material-1.4.0-beta01.aar",
          "size": 2790226,
          "sha512": "897b94ca528cefa1f6ccff9e8061e613918570285e78dcc186d6a615f2f220352fb5cc082086176bc17a30890c22e273a09168b3197f3170cab267ef0d8f8b96",
          "sha256": "2c16e9b77263d6f0c21b3934e7151c05c61ccef123ebc244be0bd4e0bdae67b1",
          "sha1": "42ece0e7c19eb92509a4445df791df73e306966c",
          "md5": "163bd891c0891bed580e3c5f90b2391e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.4.0-beta01-sources.jar",
          "url": "material-1.4.0-beta01-sources.jar",
          "size": 219249,
          "sha512": "82b31d191577add02f6c8a589aafda5a396439a0225714a54f0f05b82ca4a6b53da4ee5bca77fddf2766f46f6ca84d6401ba70ebb1d7ba4bfe87ee386e82f793",
          "sha256": "b64d1867f9da4f427ef69b8d28b6f8eedd263e6d4a9f2390bf8efd8f9eada22d",
          "sha1": "82e36a5e05e852d0fc806ff1ecaa5fc2915257e7",
          "md5": "cca7088e30e8771f28645b3e9d87119f"
        }
      ]
    }
  ]
}