{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions",
    "module": "extensions",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.1.0-beta01.aar",
          "url": "extensions-1.1.0-beta01.aar",
          "size": 34630,
          "sha512": "4773193e5892823a4fa605182945df678d28945b623b03dd74bb59979972a9b37ace783abf2fa6fb7d0ab8c5c1e7396db782eb5a6e1bdc287734a7536f697d22",
          "sha256": "7514f30c384d893270524cd6cbd8bbada7238a669d4f0713104579dc578368e2",
          "sha1": "9886ce1ef9b449d0294a7e8ed098811136860ee4",
          "md5": "1455b2e418ba13b206c1468b6ad0823a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.1.0-beta01.aar",
          "url": "extensions-1.1.0-beta01.aar",
          "size": 34630,
          "sha512": "4773193e5892823a4fa605182945df678d28945b623b03dd74bb59979972a9b37ace783abf2fa6fb7d0ab8c5c1e7396db782eb5a6e1bdc287734a7536f697d22",
          "sha256": "7514f30c384d893270524cd6cbd8bbada7238a669d4f0713104579dc578368e2",
          "sha1": "9886ce1ef9b449d0294a7e8ed098811136860ee4",
          "md5": "1455b2e418ba13b206c1468b6ad0823a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-1.1.0-beta01-sources.jar",
          "url": "extensions-1.1.0-beta01-sources.jar",
          "size": 35014,
          "sha512": "2ce83e209dc1f13e27c9d42e4cdaa39c24b46bd0f656ed30220061e711d7457d21e42883316cf351ecef347f67db364ca468a9399480075c71b0054f23c60379",
          "sha256": "94c3d3ae66ce124e9835686de4d561cf1113261917b06adb257175c254c0f9ef",
          "sha1": "94c4dbe46356ed0ff030a6313613d5c903b267b4",
          "md5": "0df06cec9feb1c5db351ff48681ef342"
        }
      ]
    }
  ]
}