{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-common",
    "version": "3.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.2.0-alpha01.jar",
          "url": "paging-common-3.2.0-alpha01.jar",
          "size": 692687,
          "sha512": "58097f3bef0cd7c5df76b70db0535b20b8cfa939533f3b21de97af2337b15ffff535ab360d6c19d22ea054ce8b911bd8caaabab854951cae1db242793f510518",
          "sha256": "e8c1849caaaaa0019964308c415cb4cc57bf07b16334dd789e9c3e2067a7e4a8",
          "sha1": "e354f436a4d6d217f7bbefaa2372691e38e064f1",
          "md5": "61cb9318e2b1492061bcaaaf6f5c941c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "paging-common-3.2.0-alpha01.jar",
          "url": "paging-common-3.2.0-alpha01.jar",
          "size": 692687,
          "sha512": "58097f3bef0cd7c5df76b70db0535b20b8cfa939533f3b21de97af2337b15ffff535ab360d6c19d22ea054ce8b911bd8caaabab854951cae1db242793f510518",
          "sha256": "e8c1849caaaaa0019964308c415cb4cc57bf07b16334dd789e9c3e2067a7e4a8",
          "sha1": "e354f436a4d6d217f7bbefaa2372691e38e064f1",
          "md5": "61cb9318e2b1492061bcaaaf6f5c941c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-common-3.2.0-alpha01-sources.jar",
          "url": "paging-common-3.2.0-alpha01-sources.jar",
          "size": 143413,
          "sha512": "cc3cc4eba4004fc1b02f462efe5aa19e8ca387e7c55967623ff24de096ea6b1a5e109ad431c16624e934f0e2a7f1a4b8c3220ea340bb6c2ffba0e6a3ecf38bf4",
          "sha256": "72c9bf5520154493d50714c2d43ab605431e9f61086e85c84fadde6a3cf75fa6",
          "sha1": "01780efd3b587208855f720aa6879ffbddb1b8a3",
          "md5": "374403f47ae0bc651a450a54c1a8a80d"
        }
      ]
    }
  ]
}
