{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.5.0-alpha03.aar",
          "url": "navigation-ui-ktx-2.5.0-alpha03.aar",
          "size": 1776,
          "sha512": "5ba88a91118c7aa07d034cd29e4c95ed6619014e757ffce4f6bc43565da64240425fea12863cb43657956f66f025ce069ccce72c9c1806fecee329f373646f03",
          "sha256": "b8212cac21be8ef35ec270ab8a34fd86d95ed785312a155206ba92ddf131b3b3",
          "sha1": "a53213c72d511d93afa2e3caf909f5fed719c01f",
          "md5": "ae0e1c9b4789f556d536b312a62a10cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.5.0-alpha03.aar",
          "url": "navigation-ui-ktx-2.5.0-alpha03.aar",
          "size": 1776,
          "sha512": "5ba88a91118c7aa07d034cd29e4c95ed6619014e757ffce4f6bc43565da64240425fea12863cb43657956f66f025ce069ccce72c9c1806fecee329f373646f03",
          "sha256": "b8212cac21be8ef35ec270ab8a34fd86d95ed785312a155206ba92ddf131b3b3",
          "sha1": "a53213c72d511d93afa2e3caf909f5fed719c01f",
          "md5": "ae0e1c9b4789f556d536b312a62a10cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.5.0-alpha03-sources.jar",
          "url": "navigation-ui-ktx-2.5.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}
