homepage: "http://www.xmlsoft.org/libxslt/"
language: c++
vendor_ccs:
  - "ddkilzer@apple.com"
  - "schenney@chromium.org"
sanitizers:
  - address
  - memory
  - undefined
main_repo: 'https://gitlab.gnome.org/GNOME/libxslt.git'
