{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-1.0.0-alpha05.aar",
          "url": "appsearch-1.0.0-alpha05.aar",
          "size": 113734,
          "sha512": "4d84c970edefa1386192f1546cfc23f14cc3308810d079e22dcd566cb6affdfc8660b847e0da6e1b228bd4537e909a1d11e90b45be46ae3371b30e9055c7ced0",
          "sha256": "33f1ce3c769be641746f02b3399d42eca651ed91da9f90c1d0e5404f01ae256d",
          "sha1": "284a4609b752e4639cf2c34534d24593d67ba9b2",
          "md5": "e883fe38c7a1e670cea6c7cbc4641863"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-1.0.0-alpha05.aar",
          "url": "appsearch-1.0.0-alpha05.aar",
          "size": 113734,
          "sha512": "4d84c970edefa1386192f1546cfc23f14cc3308810d079e22dcd566cb6affdfc8660b847e0da6e1b228bd4537e909a1d11e90b45be46ae3371b30e9055c7ced0",
          "sha256": "33f1ce3c769be641746f02b3399d42eca651ed91da9f90c1d0e5404f01ae256d",
          "sha1": "284a4609b752e4639cf2c34534d24593d67ba9b2",
          "md5": "e883fe38c7a1e670cea6c7cbc4641863"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appsearch-1.0.0-alpha05-sources.jar",
          "url": "appsearch-1.0.0-alpha05-sources.jar",
          "size": 97969,
          "sha512": "0f143f073243096d76d2e4e57ccf781a7ad0ac6578963b01f3abc99829a11e2f54a006a9112ea6fa59e9bb3daf5b136eb95a00967569bfb6a062f427c8eb3698",
          "sha256": "436ec7d8f8f96ff1ceac1ef19faee0d9f81db931d88a76a8a41a29a09184702a",
          "sha1": "3226cd59e5a3dbca69cf1acd51b9ff9a5fa7c632",
          "md5": "ad59bc1cf1c775b16878406dba861a11"
        }
      ]
    }
  ]
}
