{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.0-alpha03"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.5.0-alpha03.aar",
          "url": "fragment-ktx-1.5.0-alpha03.aar",
          "size": 20188,
          "sha512": "c44c22e10f50e6fcbd131bf4d140d7635fed213172d94557209ff1fbee73cc4c16c837ecdc1c4bf4358b0ff2afed4c9aab975f9ebf24ca1ee4a36b0345ffa7c3",
          "sha256": "16e1d08d30682762d8267cd254bce42a743ce61d10464bfb0bdf8a2e7ffa0821",
          "sha1": "6dd66f95fa0a5e0b2c507dd2ad6f6a1311971d5f",
          "md5": "3c5117bb5b647e23e0b63994c092ce7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.0-alpha03"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.5.0-alpha03.aar",
          "url": "fragment-ktx-1.5.0-alpha03.aar",
          "size": 20188,
          "sha512": "c44c22e10f50e6fcbd131bf4d140d7635fed213172d94557209ff1fbee73cc4c16c837ecdc1c4bf4358b0ff2afed4c9aab975f9ebf24ca1ee4a36b0345ffa7c3",
          "sha256": "16e1d08d30682762d8267cd254bce42a743ce61d10464bfb0bdf8a2e7ffa0821",
          "sha1": "6dd66f95fa0a5e0b2c507dd2ad6f6a1311971d5f",
          "md5": "3c5117bb5b647e23e0b63994c092ce7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-ktx-1.5.0-alpha03-sources.jar",
          "url": "fragment-ktx-1.5.0-alpha03-sources.jar",
          "size": 6289,
          "sha512": "899f68d136c326bf21f9f4c0636f1bd718417dfb9c459c09bcb58411ab21d60930864284b6f5f5b4e6b62895e9445ff5a925efa682f34713b16da4fb93a51d0f",
          "sha256": "4d97c247824b03df75569e8bef82e4cc492780930603d95a335b8cce355b7c24",
          "sha1": "0434bc83ca46f0582c78273f9fed0360ab2541d5",
          "md5": "21ceb537de65876d47c641accbfcd119"
        }
      ]
    }
  ]
}
