{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-process",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha03.aar",
          "url": "lifecycle-process-2.5.0-alpha03.aar",
          "size": 10529,
          "sha512": "d9696e98944e67ed4ab881a6896782cc7c023356f1d230744ca2e3940b29601b0eb01c7734095c90f5bafe1990a9566464598a31c51f8c210fdf6306c474064d",
          "sha256": "7a8aca8b750f4e91c5dc2373ecb83d9f4389718ebe8019280846ca44b0cf16ce",
          "sha1": "589b4461435457e937600f1f4b7850bd35068695",
          "md5": "5a58df157509840a372a6ed46575ff65"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha03.aar",
          "url": "lifecycle-process-2.5.0-alpha03.aar",
          "size": 10529,
          "sha512": "d9696e98944e67ed4ab881a6896782cc7c023356f1d230744ca2e3940b29601b0eb01c7734095c90f5bafe1990a9566464598a31c51f8c210fdf6306c474064d",
          "sha256": "7a8aca8b750f4e91c5dc2373ecb83d9f4389718ebe8019280846ca44b0cf16ce",
          "sha1": "589b4461435457e937600f1f4b7850bd35068695",
          "md5": "5a58df157509840a372a6ed46575ff65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-process-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-process-2.5.0-alpha03-sources.jar",
          "size": 5906,
          "sha512": "ce90d34c102d83719416317ec6329e10256c3a646f88afedab555f0a4957704876f8f13e086e78e5a4d734e5d1606b1e328c961e7418cfb3d0457d9c78fe7736",
          "sha256": "b40b16492aa34faed4e34fb19f8d12afb79715eeb8ef098df4c5713647cd1a42",
          "sha1": "8fccf25901f65172f1380c9abc6cbbabe809fe6a",
          "md5": "53d76930af8c714cd452d8736b32f67b"
        }
      ]
    }
  ]
}
