{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-savedstate",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-alpha03.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-alpha03.aar",
          "size": 31348,
          "sha512": "8e33ed99989ec20adda4faccaa129811320a4d1e3e0fbfc5f01cf7763791a63649dec58df45d74c443d4df008d166a7aec0ffad41a30a7e07f56e23096006aea",
          "sha256": "b5b9fe11cfda7aff25659bc311ecbdefc743ef49fd20f3ad6a04c200be5a3e78",
          "sha1": "de4b0eaed0708a47b4dbb1dd1b95ab06fb35bc59",
          "md5": "f7173aae013c2a219d50d9a7d5c148ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-alpha03.aar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-alpha03.aar",
          "size": 31348,
          "sha512": "8e33ed99989ec20adda4faccaa129811320a4d1e3e0fbfc5f01cf7763791a63649dec58df45d74c443d4df008d166a7aec0ffad41a30a7e07f56e23096006aea",
          "sha256": "b5b9fe11cfda7aff25659bc311ecbdefc743ef49fd20f3ad6a04c200be5a3e78",
          "sha1": "de4b0eaed0708a47b4dbb1dd1b95ab06fb35bc59",
          "md5": "f7173aae013c2a219d50d9a7d5c148ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-savedstate-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-viewmodel-savedstate-2.5.0-alpha03-sources.jar",
          "size": 14319,
          "sha512": "443de5ce1319210f1fc1d1f1ab1fc48a1ce450f77e250c94ae574db73ba9a12f5a83bb1da2c6540ab11f62dec746ec500135b8dc33bd3d3452143082cb155c4b",
          "sha256": "ae898ed332b4acaa8fa7be41fa06b83f856b529b6e6e2a85b8cf37820f32a790",
          "sha1": "024a925ed82a45bdc7f20897067d2d7df3e61109",
          "md5": "c9bd950bdb54af9303792c5f0eea7eff"
        }
      ]
    }
  ]
}
