{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.heifwriter",
    "module": "heifwriter",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "heifwriter-1.1.0-alpha02.aar",
          "url": "heifwriter-1.1.0-alpha02.aar",
          "size": 35027,
          "sha512": "18197c9b8094a811b3a7eb381fde8224819bec3b99cddea824afa099a2e279d207b4dafc62b2cf0c21ba7fe9f64eafb22ebd610f800be2c4c080ddde3cbacd4c",
          "sha256": "ed21159860214944c6c7bca5c651f4de2ee62268aed5aad75a96cd347735579d",
          "sha1": "f857f9fcd995a3fde1e818927c43a0fb3e13c246",
          "md5": "1e77fe888e35bd9dd45ab90e68a60b7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "heifwriter-1.1.0-alpha02.aar",
          "url": "heifwriter-1.1.0-alpha02.aar",
          "size": 35027,
          "sha512": "18197c9b8094a811b3a7eb381fde8224819bec3b99cddea824afa099a2e279d207b4dafc62b2cf0c21ba7fe9f64eafb22ebd610f800be2c4c080ddde3cbacd4c",
          "sha256": "ed21159860214944c6c7bca5c651f4de2ee62268aed5aad75a96cd347735579d",
          "sha1": "f857f9fcd995a3fde1e818927c43a0fb3e13c246",
          "md5": "1e77fe888e35bd9dd45ab90e68a60b7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "heifwriter-1.1.0-alpha02-sources.jar",
          "url": "heifwriter-1.1.0-alpha02-sources.jar",
          "size": 24913,
          "sha512": "848e8fcb9695e3fd4142ec46ff3e53aefd15cf47c71e81e2e41da43e0c3528c1b73ceb763ea237aa00fefad12013b6a79834e2f2b2123b83580d156cbae9d5d6",
          "sha256": "c2fd0c0b128bbc05171afe3aa2666488921984ca59689223a4edc1457e508f42",
          "sha1": "7d553efdba57a788fa514711b0cc93939bae27ee",
          "md5": "0792a897f51a8310c2b7750bff4c4295"
        }
      ]
    }
  ]
}
