{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime",
    "version": "3.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.2.0-alpha01"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.2.0-alpha01.aar",
          "url": "paging-runtime-3.2.0-alpha01.aar",
          "size": 75595,
          "sha512": "d2d9d4782cba00c6bca523b11f02ca335d8e0c2f945d08d1a47342db80ba609b2eb1bab5144efea8723c9dd047a552d2f565e3e69fc056bf4cec0faf16af67f8",
          "sha256": "42a2c44af5b2f509372338db0e81d4771fd3e0e87a1424dff053b747cac7f16c",
          "sha1": "aa165c57820467079230ec890f9a515e7add14ba",
          "md5": "128b18fdbe23ca8f4f43aa1394fcc115"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.2.0-alpha01"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.2.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.2.0-alpha01.aar",
          "url": "paging-runtime-3.2.0-alpha01.aar",
          "size": 75595,
          "sha512": "d2d9d4782cba00c6bca523b11f02ca335d8e0c2f945d08d1a47342db80ba609b2eb1bab5144efea8723c9dd047a552d2f565e3e69fc056bf4cec0faf16af67f8",
          "sha256": "42a2c44af5b2f509372338db0e81d4771fd3e0e87a1424dff053b747cac7f16c",
          "sha1": "aa165c57820467079230ec890f9a515e7add14ba",
          "md5": "128b18fdbe23ca8f4f43aa1394fcc115"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-3.2.0-alpha01-sources.jar",
          "url": "paging-runtime-3.2.0-alpha01-sources.jar",
          "size": 36032,
          "sha512": "67d453f155bac4a27e85e265b26660e4e9485547241d161ee17303ea40c7a30be489b32c253c6f1a085a9b5c00ee2efca375e7fe27a821831852493e5fa70f93",
          "sha256": "476fae3dc04c786eebb5810e8db714f8d4c6281b2b865baab9d1e76ad0fa1e94",
          "sha1": "4379f9bd714b051dbd90fae003cd58905df25f59",
          "md5": "dd2614cbf24217cb22874bcf730b7071"
        }
      ]
    }
  ]
}
