{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "size": 10047,
          "sha512": "7ab1b95047d03dc37441f5f64367b3c3f8f55941f78f144e081bef1d00af53cc55683e8212a35695c5673de4b5612a30ced426d7cd50a7bbc2ea923678927ce1",
          "sha256": "078f462e1685f95ef73465836b3f412dde36c6b59c6848c7f9f30206a609a3cb",
          "sha1": "db6a91b5e4f6a9823e11061988a8e1bb5a3287c3",
          "md5": "eab5f889546ab2c90bc68b08e0a21ba9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "url": "lifecycle-livedata-core-2.5.0-alpha03.aar",
          "size": 10047,
          "sha512": "7ab1b95047d03dc37441f5f64367b3c3f8f55941f78f144e081bef1d00af53cc55683e8212a35695c5673de4b5612a30ced426d7cd50a7bbc2ea923678927ce1",
          "sha256": "078f462e1685f95ef73465836b3f412dde36c6b59c6848c7f9f30206a609a3cb",
          "sha1": "db6a91b5e4f6a9823e11061988a8e1bb5a3287c3",
          "md5": "eab5f889546ab2c90bc68b08e0a21ba9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.5.0-alpha03-sources.jar",
          "url": "lifecycle-livedata-core-2.5.0-alpha03-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
