homepage: "https://github.com/apple/swift-protobuf"
language: swift
primary_contact: "tkientzle@apple.com"
auto_ccs :
- "p.antoine@catenacyber.fr"
- "thomasvl@google.com"

fuzzing_engines:
- libfuzzer
sanitizers:
- address
- thread
main_repo: 'https://github.com/apple/swift-protobuf.git'
