{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.5.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.5.0-alpha03.aar",
          "url": "navigation-ui-2.5.0-alpha03.aar",
          "size": 94710,
          "sha512": "1ab892182b8e0a675ba072b5ecbc5aeb7d4a8b7a713dc884d81b5ae1ef2bdcc956b44a1aa9b9f9511c0fd6bedc6748d8022b926a177ada19f20f2b0c4f2f2b29",
          "sha256": "4fad96999a731b76d9bfe90fc36ea08bfe1e9614d658ad3be27c60d972962d24",
          "sha1": "9fc1d5bcfa5a8bd8fc470fa42fe04f2bf8500124",
          "md5": "887392d99b8a2219b3074021607dded6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.0-alpha03"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.5.0-alpha03.aar",
          "url": "navigation-ui-2.5.0-alpha03.aar",
          "size": 94710,
          "sha512": "1ab892182b8e0a675ba072b5ecbc5aeb7d4a8b7a713dc884d81b5ae1ef2bdcc956b44a1aa9b9f9511c0fd6bedc6748d8022b926a177ada19f20f2b0c4f2f2b29",
          "sha256": "4fad96999a731b76d9bfe90fc36ea08bfe1e9614d658ad3be27c60d972962d24",
          "sha1": "9fc1d5bcfa5a8bd8fc470fa42fe04f2bf8500124",
          "md5": "887392d99b8a2219b3074021607dded6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.5.0-alpha03-sources.jar",
          "url": "navigation-ui-2.5.0-alpha03-sources.jar",
          "size": 20671,
          "sha512": "cbbe5652144d3fd8b0bbceacf08a6ccebe614f83ca59ea1bbecc025ecfbd994a3746cddd341550ea87303eae41523937282f212598722affae6ab766343f8987",
          "sha256": "1452b4fcde13f893c5139aa174eef9d17b96530d6d3174a1a8eab749519c4bf3",
          "sha1": "98d14c11b76d48f001acce8f26a1d3157b84d1ca",
          "md5": "2c1a49834e1b1dd63b96e1ffddfcf96e"
        }
      ]
    }
  ]
}
