name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: cargo fmt --check
    - name: Verify regenerated files
      run: ./scripts/unicode.py && diff tables.rs src/tables.rs