[project]
name = "mmi2grpc"
authors = [{name = "Pandora", email = "pandora-core@google.com"}]
readme = "README.md"
dynamic = ["version", "description"]
dependencies = [
    "bt-test-interfaces",
    "grpcio>=1.41",
    "numpy>=1.22",
    "scipy>=1.8"
]

[build-system]
requires = ["flit_core==3.7.1"]
build-backend = "flit_core.buildapi"
