homepage: "https://github.com/relic-toolkit/relic"
language: c++
primary_contact: "guidovranken@gmail.com"
main_repo: "https://github.com/relic-toolkit/relic"
auto_ccs:
    - "dfaranha@gmail.com"
sanitizers:
 - address
 - undefined
# Disabled MSAN because of https://github.com/google/oss-fuzz/issues/6294
#  - memory
architectures:
 - x86_64
 - i386
