// Auto-generated with: android/scripts/gen-entries.py --mode=funcargs stream-servers/OpenGLESDispatch/gles32_only.entries --output=stream-servers/OpenGLESDispatch/gles32_only_functions.h
// DO NOT EDIT THIS FILE

#ifndef GLES32_ONLY_FUNCTIONS_H
#define GLES32_ONLY_FUNCTIONS_H

#include <GLES/gl.h>
#include <GLES3/gl3.h>
#include <GLES3/gl32.h>
#define LIST_GLES32_ONLY_FUNCTIONS(X) \
  X(void, glDebugMessageControl, (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint * ids, GLboolean enabled), (source, type, severity, count, ids, enabled)) \
  X(void, glDebugMessageInsert, (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * buf), (source, type, id, severity, length, buf)) \
  X(void, glDebugMessageCallback, (GLDEBUGPROC callback, const void * userParam), (callback, userParam)) \
  X(GLuint, glGetDebugMessageLog, (GLuint count, GLsizei bufSize, GLenum * sources, GLenum * types, GLuint * ids, GLenum * severities, GLsizei * lengths, GLchar * messageLog), (count, bufSize, sources, types, ids, severities, lengths, messageLog)) \
  X(void, glPushDebugGroup, (GLenum source, GLuint id, GLsizei length, const GLchar* message), (source, id, length, message)) \
  X(void, glPopDebugGroup, (), ()) \


#endif  // GLES32_ONLY_FUNCTIONS_H
