// Auto-generated with: android/scripts/gen-entries.py --mode=funcargs stream-servers/OpenGLESDispatch/gles3_extensions.entries --output=stream-servers/OpenGLESDispatch/gles3_extensions_functions.h
// DO NOT EDIT THIS FILE

#ifndef GLES3_EXTENSIONS_FUNCTIONS_H
#define GLES3_EXTENSIONS_FUNCTIONS_H

#define LIST_GLES3_EXTENSIONS_FUNCTIONS(X) \
  X(void, glVertexAttribIPointerWithDataSize, (GLuint indx, GLint size, GLenum type, GLsizei stride, const GLvoid* ptr, GLsizei dataSize), (indx, size, type, stride, ptr, dataSize)) \
  X(void, glPrimitiveRestartIndex, (GLuint index), (index)) \


#endif  // GLES3_EXTENSIONS_FUNCTIONS_H
