// Auto-generated with: android/scripts/gen-entries.py --mode=static_translator_namespaced_header stream-servers/OpenGLESDispatch/gles32_only.entries --output=stream-servers/OpenGLESDispatch/gles32_only_static_translator_namespaced_header.h
// DO NOT EDIT THIS FILE

#pragma once

#include <GLES/gl.h>
#include <GLES3/gl3.h>
#include <GLES3/gl32.h>
namespace translator {
namespace gles2 {
GL_APICALL void GL_APIENTRY glDebugMessageControl(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint * ids, GLboolean enabled);
GL_APICALL void GL_APIENTRY glDebugMessageInsert(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * buf);
GL_APICALL void GL_APIENTRY glDebugMessageCallback(GLDEBUGPROC callback, const void * userParam);
GL_APICALL GLuint GL_APIENTRY glGetDebugMessageLog(GLuint count, GLsizei bufSize, GLenum * sources, GLenum * types, GLuint * ids, GLenum * severities, GLsizei * lengths, GLchar * messageLog);
GL_APICALL void GL_APIENTRY glPushDebugGroup(GLenum source, GLuint id, GLsizei length, const GLchar* message);
GL_APICALL void GL_APIENTRY glPopDebugGroup();
} // namespace translator
} // namespace gles2
