{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slice",
    "module": "slice-builders",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-builders-1.1.0-alpha02.aar",
          "url": "slice-builders-1.1.0-alpha02.aar",
          "size": 66499,
          "sha512": "18ae09339f88733361f5e80ad3ac09f46741ed70116ef8734578d2ad4670698f6f72c3f46d661b9b89e235dfa5d47ea1865e0ec97497a0a0c0696e6c5e073c0e",
          "sha256": "58358f9a3af7e9e71518ebe72ee4fce4383304c10b15e68f76353675c4bf0d84",
          "sha1": "99b469a98e07650af4eae5263ed8854111810cc3",
          "md5": "456b6fe5735d0317f4f92c8b0d21188f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.slice",
          "module": "slice-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-builders-1.1.0-alpha02.aar",
          "url": "slice-builders-1.1.0-alpha02.aar",
          "size": 66499,
          "sha512": "18ae09339f88733361f5e80ad3ac09f46741ed70116ef8734578d2ad4670698f6f72c3f46d661b9b89e235dfa5d47ea1865e0ec97497a0a0c0696e6c5e073c0e",
          "sha256": "58358f9a3af7e9e71518ebe72ee4fce4383304c10b15e68f76353675c4bf0d84",
          "sha1": "99b469a98e07650af4eae5263ed8854111810cc3",
          "md5": "456b6fe5735d0317f4f92c8b0d21188f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slice-builders-1.1.0-alpha02-sources.jar",
          "url": "slice-builders-1.1.0-alpha02-sources.jar",
          "size": 42693,
          "sha512": "67d076769349584dd67ae02511050a1817a4c0afd257244fc092338cd812cf2d1f11af56b2e75590aced1b0736d075771221abf984788c08acbfd7eaa2960525",
          "sha256": "2b4785a8548fbc79b9f7fac4d2ae2d0c4899dd6f2190ee108a21adefbd8bd691",
          "sha1": "e07738588c4cfe0306d06d3809f7347711ffa950",
          "md5": "a13c0f81ed91407253968f43c141c2f5"
        }
      ]
    }
  ]
}
