# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExecutionSpecificationMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ComponentSpecificationMessage_pb2 as ComponentSpecificationMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ExecutionSpecificationMessage.proto',
  package='android.vts',
  syntax='proto2',
  serialized_options=_b('\n\025com.android.vts.protoB VtsExecutionSpecificationMessage'),
  serialized_pb=_b('\n#ExecutionSpecificationMessage.proto\x12\x0b\x61ndroid.vts\x1a#ComponentSpecificationMessage.proto\"h\n\x1d\x45xecutionSpecificationMessage\x12\x37\n\rfunction_call\x18\x01 \x03(\x0b\x32 .android.vts.FunctionCallMessage\x12\x0e\n\x05valid\x18\xe8\x07 \x01(\x08\x42\x39\n\x15\x63om.android.vts.protoB VtsExecutionSpecificationMessage')
  ,
  dependencies=[ComponentSpecificationMessage__pb2.DESCRIPTOR,])




_EXECUTIONSPECIFICATIONMESSAGE = _descriptor.Descriptor(
  name='ExecutionSpecificationMessage',
  full_name='android.vts.ExecutionSpecificationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='function_call', full_name='android.vts.ExecutionSpecificationMessage.function_call', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valid', full_name='android.vts.ExecutionSpecificationMessage.valid', index=1,
      number=1000, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=193,
)

_EXECUTIONSPECIFICATIONMESSAGE.fields_by_name['function_call'].message_type = ComponentSpecificationMessage__pb2._FUNCTIONCALLMESSAGE
DESCRIPTOR.message_types_by_name['ExecutionSpecificationMessage'] = _EXECUTIONSPECIFICATIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecutionSpecificationMessage = _reflection.GeneratedProtocolMessageType('ExecutionSpecificationMessage', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTIONSPECIFICATIONMESSAGE,
  '__module__' : 'ExecutionSpecificationMessage_pb2'
  # @@protoc_insertion_point(class_scope:android.vts.ExecutionSpecificationMessage)
  })
_sym_db.RegisterMessage(ExecutionSpecificationMessage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
