homepage: "https://nginx.org/en/docs/njs/"
language: c++
primary_contact: "xeioexception@gmail.com"
auto_ccs:
 - "lex.borisov@gmail.com"
 - "devrep@nginx.com"
sanitizers:
  - address
# Disabled MSAN because of https://github.com/google/oss-fuzz/issues/6294
#  - memory
  - undefined
coverage_extra_args: -ignore-filename-regex=.*/pcre/.*
main_repo: 'https://github.com/nginx/njs.git'