{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.remotecallback",
    "module": "remotecallback",
    "version": "1.0.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "remotecallback-1.0.0-alpha02.aar",
          "url": "remotecallback-1.0.0-alpha02.aar",
          "size": 16916,
          "sha512": "1c3a84690ff58d03782de8f56dd272bfc7bc4c7fb8e8a5353456c2a21919e2ce7da5b18decc8104785af53a00c68669e2b3c8442110833a80057facef511c5f2",
          "sha256": "cc8c3aed7509177b2805b35798626cd76c414e71d566f7b897236c5b14074e43",
          "sha1": "de51ec88964b19ee976ddb82db528418ade07fb6",
          "md5": "cd56ef6521ee3ca89e01bc5f2c5eddfb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "remotecallback-1.0.0-alpha02.aar",
          "url": "remotecallback-1.0.0-alpha02.aar",
          "size": 16916,
          "sha512": "1c3a84690ff58d03782de8f56dd272bfc7bc4c7fb8e8a5353456c2a21919e2ce7da5b18decc8104785af53a00c68669e2b3c8442110833a80057facef511c5f2",
          "sha256": "cc8c3aed7509177b2805b35798626cd76c414e71d566f7b897236c5b14074e43",
          "sha1": "de51ec88964b19ee976ddb82db528418ade07fb6",
          "md5": "cd56ef6521ee3ca89e01bc5f2c5eddfb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remotecallback-1.0.0-alpha02-sources.jar",
          "url": "remotecallback-1.0.0-alpha02-sources.jar",
          "size": 14728,
          "sha512": "bec96622a6bfc6bd52a270ca0daaa22ad022ee5ada8ae6bece86061a4bf70456b151eecf3c8e71d0c7a5d36e2d4c690deaf5d1fd72e47e4b41b4514c9abb379f",
          "sha256": "3c5da416064a97e3a2eb841d5cad09708aba178f153f42e25aad8d31c918fac3",
          "sha1": "72d83957ce88ca79215f22b7818c8c29f6ca66fc",
          "md5": "bcd6fc93b61e1e739f027cfc8ee67550"
        }
      ]
    }
  ]
}
