{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch-local-storage",
    "version": "1.0.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-local-storage-1.0.0-alpha05.aar",
          "url": "appsearch-local-storage-1.0.0-alpha05.aar",
          "size": 10122588,
          "sha512": "c0f91f918fd15b0ce6777cf05026504013ea7b1a85dcd77865000798dd74ad4cac421e346f63b993264eb7f3f8d95f117c06435e9984c07280cfd574d632da79",
          "sha256": "cc9a78a2f8e6b1c39c516b19f7aa459457238b26f00eff1801a57889291f8ef6",
          "sha1": "6dea3f3a3f0e8d74e293491760f2152ca02e2dfb",
          "md5": "0735d7138b1a84f358f52ca476170dbf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.0.0-alpha05"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appsearch-local-storage-1.0.0-alpha05.aar",
          "url": "appsearch-local-storage-1.0.0-alpha05.aar",
          "size": 10122588,
          "sha512": "c0f91f918fd15b0ce6777cf05026504013ea7b1a85dcd77865000798dd74ad4cac421e346f63b993264eb7f3f8d95f117c06435e9984c07280cfd574d632da79",
          "sha256": "cc9a78a2f8e6b1c39c516b19f7aa459457238b26f00eff1801a57889291f8ef6",
          "sha1": "6dea3f3a3f0e8d74e293491760f2152ca02e2dfb",
          "md5": "0735d7138b1a84f358f52ca476170dbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appsearch-local-storage-1.0.0-alpha05-sources.jar",
          "url": "appsearch-local-storage-1.0.0-alpha05-sources.jar",
          "size": 99394,
          "sha512": "96ae0362ee6c9b35d2693056960f084b84e53cdf4ef7482364b77126e59cf319c475d7107bace433d56d854f386820bdbc3a242cd7d4024d64148f07bf47091b",
          "sha256": "963a7c3501c4ef73a6ad438ac132bd48bac8af363e8157c49863cee19dfc7ccb",
          "sha1": "701009d4fc750c8f8e842bca1a9839527ab87b0e",
          "md5": "9e242ed14eeead1dc86fbc8faf8c4407"
        }
      ]
    }
  ]
}
